"use strict";
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const {spawnSync}=require('node:child_process');
const {loadEarningsPrimary,validatePrimaryHistory,digestJSON}=require('../lib/stripe-transfer-persistence');
const {inspectHistory,importHistory}=require('../scripts/stripe-transfer-history');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'stripe-history-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.mkdirSync(path.join(dir,'wal'));
 const files={};for(const [role,value] of Object.entries({earnings:{acc_one:{pending_balance:10,processed_settlements:[]}},accounts:{acc_one:{wallet:'0xabc'}},wallet_map:{'0xabc':'acc_one'},withdrawals:'',provider_evidence:[]})){const name=role+(role==='withdrawals'?'.jsonl':'.json');const bytes=typeof value==='string'?value:JSON.stringify(value);fs.writeFileSync(path.join(dir,name),bytes);files[role]={path:name,sha256:crypto.createHash('sha256').update(bytes).digest('hex')};}
 const manifest={schema_version:1,inventory_complete:true,history_interval:{start:'2026-01-01',end:'2026-10-01'},full_provider_local_reconciliation:true,positive_history_attestation:true,platforms:[{stripe_platform:'legacy',stripe_platform_account_id:'acct_fixture_old',livemode:false,history_complete:true,unused_history_attested:true},{stripe_platform:'auxilo_llc',stripe_platform_account_id:'acct_fixture_new',livemode:false,history_complete:true,unused_history_attested:true}],files,wal:{path:'wal',files:[],listing_sha256:digestJSON([])}};
 const manifestPath=path.join(dir,'manifest.json');fs.writeFileSync(manifestPath,JSON.stringify(manifest));return {dir,manifest,manifestPath};}
function persist(f){fs.writeFileSync(f.manifestPath,JSON.stringify(f.manifest));}
test('D06S strict primary missing empty corrupt never consults older backup',t=>{const {dir}=fixture(t);const file=path.join(dir,'primary.json');const backup=file+'.bak';fs.writeFileSync(backup,'{}');for(const bytes of [null,'','{']){if(bytes!==null)fs.writeFileSync(file,bytes);assert.throws(()=>loadEarningsPrimary(file));if(bytes!==null)assert.equal(fs.readFileSync(file,'utf8'),bytes);assert.equal(fs.readFileSync(backup,'utf8'),'{}');}});
test('D06S crash child preserves authoritative primary and backup bytes',t=>{const {dir}=fixture(t);const file=path.join(dir,'primary.json');fs.writeFileSync(file,'{');fs.writeFileSync(file+'.bak','{}');const modulePath=require.resolve('../lib/stripe-transfer-persistence');const child=spawnSync(process.execPath,['-e',`require(${JSON.stringify(modulePath)}).loadEarningsPrimary(${JSON.stringify(file)})`],{env:{...process.env,HOME:dir,AUXILO_HOME:dir,AUXILO_RUNNER_AUTOUPDATE:'0'}});assert.notEqual(child.status,0);assert.equal(fs.readFileSync(file,'utf8'),'{');assert.equal(fs.readFileSync(file+'.bak','utf8'),'{}');});
test('D06S missing applied marker and missing completed receipt are rollback evidence',()=>{const a={attempt_id:'fixture',state:'ledger_applied',account_id:'acc_one',earnings_key_at_creation:'acc_one'};assert.throws(()=>validatePrimaryHistory({earnings:{acc_one:{processed_settlements:[]}},attempts:[a],receipts:[]}),/marker/i);const earnings={acc_one:{processed_settlements:['stripe-transfer-attempt:fixture']}};assert.equal(validatePrimaryHistory({earnings,attempts:[a],receipts:[]}),true);assert.throws(()=>validatePrimaryHistory({earnings,attempts:[{...a,state:'completed'}],receipts:[]}),/receipt/i);assert.equal(validatePrimaryHistory({earnings:{},attempts:[{...a,state:'confirmed'}],receipts:[]}),true);});
test('D11 dry run complete unused history is read-only and permits explicit fixture initialization',t=>{const f=fixture(t);const before=fs.readFileSync(path.join(f.dir,'earnings.json'),'utf8');const report=inspectHistory({dataDir:f.dir,manifestPath:f.manifestPath});assert.equal(report.ready,true);assert.equal(fs.existsSync(path.join(f.dir,'stripe-transfer-attempts.json')),false);const result=importHistory({dataDir:f.dir,manifestPath:f.manifestPath,isolatedFixture:true,approved:true});assert.equal(result.imported,0);assert.equal(fs.readFileSync(path.join(f.dir,'earnings.json'),'utf8'),before);});
test('D11 absent or checksum-broken mandatory inventory fails closed',t=>{const f=fixture(t);fs.unlinkSync(path.join(f.dir,'accounts.json'));assert.throws(()=>inspectHistory({dataDir:f.dir,manifestPath:f.manifestPath}),/inventory|ENOENT|file/i);});
test('D11 empty WAL without full provider history never proves empty inventory',t=>{const f=fixture(t);f.manifest.full_provider_local_reconciliation=false;persist(f);assert.throws(()=>inspectHistory({dataDir:f.dir,manifestPath:f.manifestPath}),/history|reconciliation/i);});
test('D11 WAL inventory omission and path escape are rejected',t=>{const f=fixture(t);fs.writeFileSync(path.join(f.dir,'wal','extra.wal.json'),'{}');assert.throws(()=>inspectHistory({dataDir:f.dir,manifestPath:f.manifestPath}),/listing|inventory/i);f.manifest.files.accounts.path='../outside.json';persist(f);assert.throws(()=>inspectHistory({dataDir:f.dir,manifestPath:f.manifestPath}),/path|outside/i);});
test('D11 uncertain legacy ledger step imports once without changing WAL or earnings',t=>{const f=fixture(t);const wal={id:'legacy-fixture',operation:'withdraw_stripe',payload:{withdrawal_id:'wd_fixture',account_id:'acc_one',earnings_key:'acc_one',amount_usd:10,net_amount_cents:975,stripe_connect_id:'acct_destination'},steps_completed:['earnings_deducted']};const bytes=JSON.stringify(wal);fs.writeFileSync(path.join(f.dir,'wal','legacy-fixture.wal.json'),bytes);f.manifest.wal.files=[{path:'legacy-fixture.wal.json',sha256:crypto.createHash('sha256').update(bytes).digest('hex'),stripe_platform:'legacy'}];f.manifest.wal.listing_sha256=digestJSON(['legacy-fixture.wal.json']);f.manifest.platforms[0].unused_history_attested=false;persist(f);const before=fs.readFileSync(path.join(f.dir,'earnings.json'),'utf8');const first=importHistory({dataDir:f.dir,manifestPath:f.manifestPath,isolatedFixture:true,approved:true});assert.equal(first.imported,1);assert.equal(importHistory({dataDir:f.dir,manifestPath:f.manifestPath,isolatedFixture:true,approved:true}).imported,0);assert.equal(fs.readFileSync(path.join(f.dir,'wal','legacy-fixture.wal.json'),'utf8'),bytes);assert.equal(fs.readFileSync(path.join(f.dir,'earnings.json'),'utf8'),before);const state=JSON.parse(fs.readFileSync(path.join(f.dir,'stripe-transfer-attempts.json'),'utf8'));assert.equal(Object.values(state.attempts)[0].historical,true);assert.equal(Object.values(state.attempts)[0].state,'unknown');});
test('D11 import requires explicit isolated approval and rejects symlink inventory',t=>{const f=fixture(t);assert.throws(()=>importHistory({dataDir:f.dir,manifestPath:f.manifestPath}),/isolated|approval/i);fs.renameSync(path.join(f.dir,'accounts.json'),path.join(f.dir,'accounts-real.json'));fs.symlinkSync(path.join(f.dir,'accounts-real.json'),path.join(f.dir,'accounts.json'));assert.throws(()=>inspectHistory({dataDir:f.dir,manifestPath:f.manifestPath}),/symlink/i);});


// Execute the real server entrypoint, with copied libraries so even legacy
// module-relative defaults remain inside the temporary fixture.
const {stageServer,reservePort,bootServer,stopServer}=require('./helpers/staged-server');
const {initializeAttemptStore,createAttemptStore}=require('../lib/stripe-transfer-attempts');
const {verifyTransferEvidence}=require('../lib/stripe-transfer-reconcile');
function stageBoot(t,port=38461){
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'d0-history-boot-'));t.after(()=>fs.rmSync(tmp,{recursive:true,force:true}));
 const repoRoot=path.join(__dirname,'..');const nodeModulesDir=path.join(repoRoot,'node_modules');
 const staged=stageServer({repoRoot,tmpDir:tmp,nodeModulesDir,port,rootFiles:['server.js','seed-knowledge.json','skills.json','openapi.json','package.json','model_config.json'],linkDirs:[],copyDirs:['lib','public','prompts','config']});
 const data=staged.dataDir;fs.mkdirSync(path.join(data,'backups'),{recursive:true});
 fs.writeFileSync(path.join(data,'accounts.json'),JSON.stringify({acc_one:{id:'acc_one',wallet:null}}));fs.writeFileSync(path.join(data,'learnings.json'),'[]');fs.writeFileSync(path.join(data,'withdrawals.jsonl'),'');
 const networkGuard=path.join(tmp,'offline-guard.js'),callsFile=path.join(tmp,'provider-create-count');fs.writeFileSync(callsFile,'0');
 fs.writeFileSync(networkGuard,`const fs=require('fs'),Module=require('module'),original=Module._load;Module._load=function(name,...args){const value=original.call(this,name,...args);if(name==='stripe'){return class extends value{constructor(...xs){super(...xs);this.transfers.create=()=>{const f=${JSON.stringify(callsFile)};fs.writeFileSync(f,String(Number(fs.readFileSync(f,'utf8'))+1));throw new Error('Provider action forbidden in boot fixture');};}};}return value;};const h=require('https');h.request=h.get=()=>{throw new Error('Outbound network forbidden in boot fixture');};global.fetch=async()=>{throw new Error('Outbound network forbidden in boot fixture');};`);
 const env={NODE_OPTIONS:'--require '+networkGuard,STRIPE_SECRET_KEY:'',STRIPE_WEBHOOK_SECRET:'',RESEND_API_KEY:'',OPS_ALERT_EMAIL:'',PRIVATE_KEY:'',PATH:process.env.PATH,HOME:tmp,AUXILO_HOME:tmp,AUXILO_DATA_DIR:data,AUXILO_WAL_DIR:path.join(data,'wal'),AUXILO_STRIPE_TRANSFER_ATTEMPTS_FILE:path.join(data,'stripe-transfer-attempts.json'),AUXILO_RUNNER_AUTOUPDATE:'0',NODE_ENV:'test',TEST_MODE:'1',PAYMENTS_ENABLED:'false',CUSTODIAL_WITHDRAW_ENABLED:'false',LLM_SENSITIVITY_ENABLED:'false',CONTENT_MODERATION_ENABLED:'true',WALLET_PRIVATE_KEY:'0x'+'11'.repeat(32),SESSION_SECRET:'d0-history-fixture-session-secret-32-bytes'};
 return {tmp,data,env,callsFile,primary:path.join(data,'earnings.json'),backup:path.join(data,'backups','earnings.json-fixture.json')};
}
function stageAttempt(f,state){
 const manifest={sha256:'a'.repeat(64),inventory_complete:true,positive_history_attestation:true,history_interval:{start:'2026-01-01',end:'2026-10-01'},platforms:[{stripe_platform:'legacy',stripe_platform_account_id:'acct_fixture_old',livemode:false},{stripe_platform:'auxilo_llc',stripe_platform_account_id:'acct_fixture_new',livemode:false}]};
 initializeAttemptStore(f.env.AUXILO_STRIPE_TRANSFER_ATTEMPTS_FILE,manifest);const store=createAttemptStore({file:f.env.AUXILO_STRIPE_TRANSFER_ATTEMPTS_FILE});
 const context={stripe_platform:'legacy',stripe_platform_account_id:'acct_fixture_old',configuration_generation:'fixture',livemode:false};
 let a=store.prepare({...context,account_id:'acc_one',earnings_key_at_creation:'acc_one',wallet_at_creation:null,client_request_key:crypto.randomUUID(),stripe_connect_id:'acct_destination',amount_usd:10,net_amount_cents:975,currency:'usd'});
 a=store.transition(a.attempt_id,a.generation,'submitted');const evidence=verifyTransferEvidence(a,{id:'tr_fixture',object:'transfer',amount:975,currency:'usd',destination:'acct_destination',livemode:false,metadata:{auxilo_transfer_attempt_id:a.attempt_id,auxilo_request_digest:a.request_digest}},context);
 a=store.transition(a.attempt_id,a.generation,'confirmed',{stripe_transfer_id:evidence.stripe_transfer_id,provider_evidence:evidence});
 if(state!=='confirmed'){
  const record={id:a.withdrawal_id,account_id:a.account_id,rail:'stripe',attempt_id:a.attempt_id,request_digest:a.request_digest,amount_usd:10,amount_cents:1000,net_amount_usd:9.75,net_amount_cents:975,stripe_fee_cents:25,stripe_transfer_id:'tr_fixture',stripe_connect_id:a.stripe_connect_id,stripe_platform:a.stripe_platform,stripe_platform_account_id:a.stripe_platform_account_id,timestamp:a.prepared_at};
  a=store.transition(a.attempt_id,a.generation,'ledger_applied',{receipt_record:record,receipt_digest:digestJSON(record),receipt:{transfer_id:'tr_fixture',amount_requested_usd:10,fee_usd:0.25,amount_transferred_usd:9.75,remaining_balance:0,attempt_id:a.attempt_id,status:'completed'}});
  if(state==='completed')a=store.transition(a.attempt_id,a.generation,'completed');
 }
 fs.writeFileSync(path.join(f.data,'wal','fixture.wal.json'),JSON.stringify({id:'fixture',operation:'withdraw_stripe_v2',payload:{attempt_id:a.attempt_id,request_digest:a.request_digest},steps_completed:[],created_at:1}));return a;
}
for(const [label,bytes] of [['missing',null],['empty',''],['corrupt','{']])test('D06S real server exits on '+label+' primary before migration or backup restore',{timeout:20000},t=>{
 const f=stageBoot(t);if(bytes!==null)fs.writeFileSync(f.primary,bytes);else if(fs.existsSync(f.primary))fs.unlinkSync(f.primary);fs.writeFileSync(f.backup,'{"acc_one":{"pending_balance":50}}');
 const backup=fs.readFileSync(f.backup,'utf8');const child=spawnSync(process.execPath,['server.js'],{cwd:f.tmp,env:f.env,encoding:'utf8',timeout:15000});
 assert.equal(child.status,1,child.stderr+child.stdout);assert.match(child.stderr,/Fatal financial storage failure/);assert.equal(child.signal,null);assert.equal(fs.readFileSync(f.backup,'utf8'),backup);assert.equal(fs.existsSync(f.primary),bytes!==null);if(bytes!==null)assert.equal(fs.readFileSync(f.primary,'utf8'),bytes);
 assert.doesNotMatch(child.stdout,/Restored earnings|migrated|WAL Recovery|listening/i);
});
for(const mode of ['missing-marker','missing-completed-receipt'])test('D06S real server refuses '+mode+' and preserves ledger bytes',{timeout:20000},t=>{
 const f=stageBoot(t),a=stageAttempt(f,mode==='missing-marker'?'ledger_applied':'completed');const entry={account_id:'acc_one',pending_balance:0,total_withdrawn:10,withdrawal_count:1,processed_settlements:mode==='missing-marker'?[]:['stripe-transfer-attempt:'+a.attempt_id]};
 const primary=JSON.stringify({acc_one:entry});fs.writeFileSync(f.primary,primary);fs.writeFileSync(f.backup,'{}');const child=spawnSync(process.execPath,['server.js'],{cwd:f.tmp,env:f.env,encoding:'utf8',timeout:15000});assert.equal(child.status,1,child.stderr+child.stdout);assert.match(child.stderr,/Fatal financial storage failure/);assert.equal(fs.readFileSync(f.primary,'utf8'),primary);assert.equal(fs.readFileSync(f.backup,'utf8'),'{}');assert.equal(fs.readFileSync(path.join(f.data,'withdrawals.jsonl'),'utf8'),'');
});
for(const state of ['confirmed','ledger_applied'])test('D06S real server recovers legitimate '+state+' exactly once with no provider send',{timeout:90000},async t=>{
 const reservation=await reservePort();if(reservation.skipReason){t.skip(reservation.skipReason);return;}
 const f=stageBoot(t,reservation.port),a=stageAttempt(f,state);const applied=state==='ledger_applied';const entry={account_id:'acc_one',wallet:null,pending_balance:applied?0:10,total_withdrawn:applied?10:0,total_contributor:10,withdrawal_count:applied?1:0,processed_settlements:applied?['stripe-transfer-attempt:'+a.attempt_id]:[],by_learning:{}};
 fs.writeFileSync(f.primary,JSON.stringify({acc_one:entry}));fs.writeFileSync(f.backup,'{}');
 const boot=await bootServer({tmpDir:f.tmp,port:reservation.port,env:f.env,timeoutMs:30000,maxAttempts:1});t.after(()=>stopServer(boot.child));if(boot.skipReason){t.skip(boot.skipReason);return;}
 assert.ok(boot.baseUrl,boot.output);assert.equal(fs.readFileSync(f.callsFile,'utf8'),'0');const disk=JSON.parse(fs.readFileSync(f.primary,'utf8'));assert.equal(disk.acc_one.pending_balance,0);assert.equal(disk.acc_one.withdrawal_count,1);assert.equal(disk.acc_one.total_withdrawn,10);
 const reloaded=createAttemptStore({file:f.env.AUXILO_STRIPE_TRANSFER_ATTEMPTS_FILE});assert.equal(reloaded.get(a.attempt_id).state,'completed');assert.equal(fs.readFileSync(path.join(f.data,'withdrawals.jsonl'),'utf8').trim().split('\n').length,1);assert.equal(fs.readFileSync(f.backup,'utf8'),'{}');
 await stopServer(boot.child);
});

function setInventoryFile(f,role,value){const file=path.join(f.dir,f.manifest.files[role].path);const bytes=role==='withdrawals'?value.map(v=>JSON.stringify(v)+'\n').join(''):JSON.stringify(value);fs.writeFileSync(file,bytes);f.manifest.files[role].sha256=crypto.createHash('sha256').update(bytes).digest('hex');persist(f);}
for(const mismatch of ['currency','amount_usd','stripe_connect_id','account_id'])test('D11 historical '+mismatch+' contradiction cannot be omitted as resolved',t=>{
 const f=fixture(t);f.manifest.platforms[0].unused_history_attested=false;
 const receipt={id:'wd_legacy',rail:'stripe',account_id:'acc_one',amount_usd:10,net_amount_cents:975,stripe_connect_id:'acct_destination',stripe_transfer_id:'tr_fixture',stripe_platform:'legacy'};
 const evidence={local_id:receipt.id,evidence_ref:'provider-fixture',stripe_platform:'legacy',stripe_platform_account_id:'acct_fixture_old',livemode:false,account_id:'acc_one',amount_usd:10,net_amount_cents:975,stripe_connect_id:'acct_destination',transfer_id:'tr_fixture',currency:'usd',transfer_confirmed:true,ledger_reviewed:true,ledger_disposition:'debited',ledger_evidence_ref:'independent-ledger-fixture'};
 evidence[mismatch]={currency:'eur',amount_usd:11,stripe_connect_id:'acct_other',account_id:'acc_other'}[mismatch];setInventoryFile(f,'withdrawals',[receipt]);setInventoryFile(f,'provider_evidence',[evidence]);const result=inspectHistory({dataDir:f.dir,manifestPath:f.manifestPath});assert.equal(result.ready,false);assert.equal(result.records.length,1);assert.ok(result.counts.conflicts>0);assert.equal(result.counts.confirmed_sent_debited,0);
});
test('D11 legacy receipts without rail remain unresolved and defeat unused-history claims',t=>{
 const f=fixture(t);setInventoryFile(f,'withdrawals',[{id:'wd_old',account_id:'acc_one',amount_usd:10,net_amount_cents:975,stripe_connect_id:'acct_destination'}]);assert.throws(()=>inspectHistory({dataDir:f.dir,manifestPath:f.manifestPath}),/unused.*contradict/i);
 f.manifest.platforms[0].unused_history_attested=false;persist(f);const result=inspectHistory({dataDir:f.dir,manifestPath:f.manifestPath});assert.equal(result.records.length,1);assert.equal(result.ready,false);assert.equal(result.counts.unknown_send,1);
});

test('D12 completed reviewed legacy history retains checksum-backed WAL disposition without changing bytes',t=>{
 const f=fixture(t);f.manifest.platforms[0].unused_history_attested=false;
 const receipt={id:'wd_resolved',rail:'stripe',account_id:'acc_one',amount_usd:10,net_amount_cents:975,stripe_connect_id:'acct_destination',stripe_transfer_id:'tr_fixture',stripe_platform:'legacy'};
 const evidence={local_id:receipt.id,evidence_ref:'provider-reviewed-fixture',stripe_platform:'legacy',stripe_platform_account_id:'acct_fixture_old',livemode:false,account_id:'acc_one',amount_usd:10,net_amount_cents:975,stripe_connect_id:'acct_destination',transfer_id:'tr_fixture',currency:'usd',transfer_confirmed:true,ledger_reviewed:true,ledger_disposition:'debited',ledger_evidence_ref:'independent-ledger-fixture'};
 const wal={id:'legacy-complete',operation:'withdraw_stripe',payload:{withdrawal_id:receipt.id,account_id:'acc_one',earnings_key:'acc_one',amount_usd:10,net_amount_cents:975,stripe_connect_id:'acct_destination'},steps_completed:['earnings_deducted','withdrawal_appended']};
 const bytes=JSON.stringify(wal),sha256=crypto.createHash('sha256').update(bytes).digest('hex');fs.writeFileSync(path.join(f.dir,'wal','legacy-complete.wal.json'),bytes);f.manifest.wal.files=[{path:'legacy-complete.wal.json',sha256,stripe_platform:'legacy'}];f.manifest.wal.listing_sha256=digestJSON(['legacy-complete.wal.json']);setInventoryFile(f,'withdrawals',[receipt]);setInventoryFile(f,'provider_evidence',[evidence]);
 const result=importHistory({dataDir:f.dir,manifestPath:f.manifestPath,isolatedFixture:true,approved:true});assert.equal(result.ready,true);assert.equal(result.imported,0);const store=createAttemptStore({file:path.join(f.dir,'stripe-transfer-attempts.json')});assert.deepEqual(store.manifest.resolved_legacy_wal,[{id:'legacy-complete',sha256,receipt_digest:digestJSON(receipt),evidence_ref:evidence.evidence_ref}]);assert.equal(fs.readFileSync(path.join(f.dir,'wal','legacy-complete.wal.json'),'utf8'),bytes);
});

test('D12 real server retains resolved legacy WAL and holds changed or unknown evidence',{timeout:90000},async t=>{
 for(const disposition of ['resolved','changed','unknown']){
  const reservation=await reservePort();if(reservation.skipReason){t.skip(reservation.skipReason);return;}
  const source=fixture(t);source.manifest.platforms[0].unused_history_attested=false;
  const receipt={id:'wd_legacy_boot',rail:'stripe',account_id:'acc_one',amount_usd:10,net_amount_cents:975,stripe_connect_id:'acct_destination',stripe_transfer_id:'tr_fixture',stripe_platform:'legacy'};
  const evidence={local_id:receipt.id,evidence_ref:'reviewed-boot-provider',stripe_platform:'legacy',stripe_platform_account_id:'acct_fixture_old',livemode:false,account_id:'acc_one',amount_usd:10,net_amount_cents:975,stripe_connect_id:'acct_destination',transfer_id:'tr_fixture',currency:'usd',transfer_confirmed:true,ledger_reviewed:true,ledger_disposition:'debited',ledger_evidence_ref:'reviewed-independent-ledger'};
  const wal={id:'legacy_boot',operation:'withdraw_stripe',payload:{withdrawal_id:receipt.id,account_id:'acc_one',earnings_key:'acc_one',amount_usd:10,net_amount_cents:975,stripe_connect_id:'acct_destination'},steps_completed:['earnings_deducted','withdrawal_appended']};
  const original=JSON.stringify(wal);fs.writeFileSync(path.join(source.dir,'wal','legacy_boot.wal.json'),original);source.manifest.wal.files=[{path:'legacy_boot.wal.json',sha256:crypto.createHash('sha256').update(original).digest('hex'),stripe_platform:'legacy'}];source.manifest.wal.listing_sha256=digestJSON(['legacy_boot.wal.json']);
  setInventoryFile(source,'earnings',{acc_one:{account_id:'acc_one',wallet:null,pending_balance:0,total_contributor:10,total_withdrawn:10,withdrawal_count:1,processed_settlements:[],by_learning:{}}});setInventoryFile(source,'withdrawals',[receipt]);setInventoryFile(source,'provider_evidence',disposition==='unknown'?[]:[evidence]);
  importHistory({dataDir:source.dir,manifestPath:source.manifestPath,isolatedFixture:true,approved:true});
  const f=stageBoot(t,reservation.port);for(const file of ['earnings.json','accounts.json','withdrawals.jsonl','stripe-transfer-attempts.json'])fs.copyFileSync(path.join(source.dir,file),path.join(f.data,file));
  const bytes=disposition==='changed'?original+'\n':original;const walPath=path.join(f.data,'wal','legacy_boot.wal.json');fs.writeFileSync(walPath,bytes);
  const boot=await bootServer({tmpDir:f.tmp,port:reservation.port,env:f.env,timeoutMs:30000,maxAttempts:1});t.after(()=>stopServer(boot.child));if(boot.skipReason){t.skip(boot.skipReason);return;}
  const health=await (await fetch(boot.baseUrl+'/health')).json();assert.equal(health.stripe_transfer_ready,disposition==='resolved',disposition);assert.equal(fs.readFileSync(walPath,'utf8'),bytes);assert.equal(fs.readFileSync(f.callsFile,'utf8'),'0');const ledger=JSON.parse(fs.readFileSync(f.primary,'utf8'));assert.equal(ledger.acc_one.total_withdrawn,10);assert.equal(ledger.acc_one.withdrawal_count,1);await stopServer(boot.child);
 }
});
