'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const {createCheckoutAdmission}=require('../lib/stripe-checkout-admission');
const {initializeCheckoutIntents,createCheckoutIntentStore}=require('../lib/stripe-checkout-intents');
const ref={checkpoint_id:'cp',manifest_sha256:'a'.repeat(64),inventory_complete:true,approval_ref:'approved-fixture'};
function fixture(t,options={}){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'checkout-admission-')),file=path.join(dir,'intents.json');t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 if(!options.missing)initializeCheckoutIntents(file,ref);const intents=createCheckoutIntentStore({file});
 const context={stripe_platform:'legacy',stripe_platform_account_id:'acct_1TCbMe0Jj0R41QQV',livemode:false,configuration_generation:'fixture'};
 let tail=Promise.resolve(),calls=0,capWrites=0;const events=[];
 const d={intents,control:()=>({intake_platform:context.stripe_platform,generation:1}),getContext:async()=>context,lock:async()=>{const prior=tail;let release;tail=new Promise(r=>release=r);await prior;return release;},checkCaps(){},reserve:()=>{capWrites++;if(options.reserveFails)throw Error('disk failure');return'resv_test';},promote:()=>{if(options.promoteFails)throw Error('disk failure');capWrites++;},createSession:async(...args)=>{calls++;events.push(intents.all()[0]);if(options.create)return options.create({intents,context,args});if(options.timeout)throw Error('timeout');return{session_id:'cs_test_a',url:'https://checkout.stripe.test/a',expires_at:Math.floor(Date.now()/1000)+600};}};
 const admit=createCheckoutAdmission(d),request={accountId:'owner',packId:'starter',amountUsd:10,baseUrl:'https://example.test'};
 return{dir,file,intents,context,d,request,admit:patch=>admit({...request,...patch}),calls:()=>calls,capWrites:()=>capWrites,events};
}
test('initial provider create occurs after durable intent submission exactly once',async t=>{const f=fixture(t);const a=await f.admit();assert.equal(a.session_id,'cs_test_a');assert.equal(f.calls(),1);assert.equal(f.events[0].state,'submitted');assert.ok(f.events[0].idempotency_key);assert.equal(f.intents.all()[0].state,'confirmed_open');});
test('same known open request reuses recorded session without another provider call',async t=>{const f=fixture(t),a=await f.admit(),b=await f.admit();assert.deepEqual(b,a);assert.equal(f.calls(),1);});
test('provider response loss blocks same and different pack after restart and cap expiry',async t=>{const f=fixture(t,{timeout:true});await assert.rejects(f.admit(),e=>e.code==='CHECKOUT_RECONCILIATION_REQUIRED'&&e.attempt_id===f.intents.all()[0].intent_id);assert.equal(f.intents.all()[0].state,'unknown');f.d.intents=createCheckoutIntentStore({file:f.file});await assert.rejects(f.admit(),/CHECKOUT_RECONCILIATION_REQUIRED/);f.context.stripe_platform='auxilo_llc';f.context.stripe_platform_account_id='acct_1UMsxYLVAUzbAOHI';await assert.rejects(f.admit({packId:'growth',amountUsd:25}),/CHECKOUT_RECONCILIATION_REQUIRED/);assert.equal(f.calls(),1);});
test('reservation durability failure leaves prepared hold and makes zero provider writes',async t=>{const f=fixture(t,{reserveFails:true});await assert.rejects(f.admit(),e=>e.code==='CHECKOUT_RECONCILIATION_REQUIRED'&&e.attempt_id===f.intents.all()[0].intent_id);assert.equal(f.calls(),0);assert.equal(f.intents.all()[0].state,'prepared');await assert.rejects(f.admit(),/CHECKOUT_RECONCILIATION_REQUIRED/);});
test('provider success followed by cap persistence failure stays unknown',async t=>{const f=fixture(t,{promoteFails:true});await assert.rejects(f.admit(),e=>e.code==='CHECKOUT_RECONCILIATION_REQUIRED'&&e.attempt_id===f.intents.all()[0].intent_id);assert.equal(f.calls(),1);assert.equal(f.intents.all()[0].state,'unknown');await assert.rejects(f.admit(),/CHECKOUT_RECONCILIATION_REQUIRED/);assert.equal(f.calls(),1);});
test('missing store produces zero provider and cap writes',async t=>{const f=fixture(t,{missing:true});await assert.rejects(f.admit(),/CHECKOUT_RECONCILIATION_REQUIRED/);assert.equal(f.calls(),0);assert.equal(f.capWrites(),0);});
test('concurrent retries of same logical request share one initial create',async t=>{const f=fixture(t);const results=await Promise.all([f.admit(),f.admit(),f.admit()]);assert.equal(f.calls(),1);assert.deepEqual(results[0],results[2]);});
test('changed control during platform lookup creates nothing',async t=>{const f=fixture(t);let reads=0;f.d.control=()=>({intake_platform:'legacy',generation:++reads});await assert.rejects(f.admit(),/MIGRATION_STATE_CHANGED/);assert.equal(f.calls(),0);assert.equal(f.intents.all().length,0);});
test('expired local open timestamp requires authoritative resolution',async t=>{const f=fixture(t,{create:async()=>({session_id:'cs_test_expired',url:'https://checkout.stripe.test/a',expires_at:Math.floor(Date.now()/1000)-1})});await f.admit();await assert.rejects(f.admit(),/CHECKOUT_RECONCILIATION_REQUIRED/);assert.equal(f.calls(),1);});
test('paid webhook racing create response cannot regress to open or double credit',async t=>{const f=fixture(t,{create:async({intents,context})=>{const a=intents.all()[0];intents.transition(a.intent_id,a.generation,'paid_pending_credit',{session_id:'cs_test_paid',evidence:{verified:true,authoritative:true,evidence_ref:'signed-paid',intent_id:a.intent_id,account_id:a.account_id,amount_cents:a.amount_cents,currency:a.currency,session_id:'cs_test_paid',stripe_platform:a.stripe_platform,stripe_platform_account_id:a.stripe_platform_account_id,livemode:a.livemode}});intents.recordPaid(context,'cs_test_paid','purchase');return{session_id:'cs_test_paid',url:'https://checkout.stripe.test/a',expires_at:Math.floor(Date.now()/1000)+600};}});await assert.rejects(f.admit(),e=>e.code==='CHECKOUT_RECONCILIATION_REQUIRED'&&e.attempt_id===f.intents.all()[0].intent_id);assert.equal(f.intents.all()[0].state,'paid_credited');assert.equal(f.calls(),1);});
for(const page of ['pricing','dashboard'])test('M09A '+page+' renders reconciliation 409 and sends only one POST',async()=>{
 const vm=require('node:vm'),source=fs.readFileSync(path.join(__dirname,'..','public',page+'.html'),'utf8');
 const start=source.indexOf('window.auxiloBuyCredits = function'),end=source.indexOf('\n  };',start)+6;assert.ok(start>=0&&end>start);
 const calls=[],alerts=[],button={disabled:false,textContent:'Buy pack'},message='Your earlier checkout could not be confirmed. New funding is paused while it is reconciled.';
 const fetch=async(url,opts)=>{calls.push({url,opts});return{ok:false,status:409,json:async()=>({code:'CHECKOUT_RECONCILIATION_REQUIRED',error:message,attempt_id:'local-intent'})};};
 const context={window:{alert:text=>alerts.push(text),location:'unchanged'},document:{querySelector:()=>button},auxiloGetToken:()=> 'synthetic-token',fetch,apiFetch:fetch,showAlert:(_id,text)=>alerts.push(text),JSON};
 vm.createContext(context);vm.runInContext(source.slice(start,end),context);context.window.auxiloBuyCredits('starter',button);
 for(let i=0;i<3;i++)await new Promise(resolve=>setImmediate(resolve));
 assert.equal(calls.length,1);assert.equal(calls[0].url,'/checkout/session');assert.equal(calls[0].opts.method,'POST');assert.deepEqual(alerts,[message]);assert.equal(context.window.location,'unchanged');assert.equal(button.disabled,false);
});
