 'use strict';
const {test,describe,before,after}=require('node:test');
const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const http=require('node:http');
const {reservePort,stageServer,bootServer,stopServer}=require('./helpers/staged-server');
const {digestJSON}=require('../lib/stripe-transfer-persistence');
const ROOT=path.join(__dirname,'..');const source=fs.readFileSync(path.join(ROOT,'server.js'),'utf8');
const MISSING=['withdrawals.jsonl','account-holds.json','checkout-sessions.json','stripe-transfer-attempts.json'];
const REQUIRED=['earnings.json','accounts.json','credits.json','purchases.jsonl'];
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const KEY='axl_r_synthetic_serving_fixture';const secret='synthetic-session-'.repeat(5);const whLegacy='whsec_'+'a'.repeat(32),whNew='whsec_'+'b'.repeat(32);
function signed(raw,hook=whLegacy){const t=Math.floor(Date.now()/1000);return `t=${t},v1=${crypto.createHmac('sha256',hook).update(`${t}.${raw}`).digest('hex')}`;}
function event(id='evt_fixture'){return {id,type:'checkout.session.completed',livemode:false,created:Math.floor(Date.now()/1000),data:{object:{id:'cs_fixture',object:'checkout.session',metadata:{private_fixture:'must-not-leak'},payment_status:'paid',amount_total:1000}}};}
function originals(dir){return Object.fromEntries([...REQUIRED,...MISSING,'settlements.jsonl','magic_links.json','wal/pending.wal.json','wal/reversal.wal.json'].map(n=>[n,fs.existsSync(path.join(dir,n))?fs.readFileSync(path.join(dir,n)).toString('base64'):null]));}
test('coverage boot assertion precedes every application import',()=>assert.match(source,/^const historyCoverage = require\('\.\/lib\/stripe-history-coverage'\);\s*historyCoverage.assertHistoryCoverageBoot\(\);/));
test('all financial migration actions explicitly reject unknown history',()=>{assert.match(fs.readFileSync(path.join(ROOT,'lib/stripe-migration-controls.js'),'utf8'),/historical_coverage === 'unknown'/);assert.match(fs.readFileSync(path.join(ROOT,'lib/payments-switch.js'),'utf8'),/historyFinancialBlocked/);});
describe('actual paused serving runtime preserves pre-D0 evidence',{timeout:60000},()=>{
 let tmp,dir,boot,port,beforeBytes,env,plan;
 before(async()=>{
  const reserved=await reservePort();assert.ok(reserved.port,'loopback required for this proof');port=reserved.port;tmp=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'auxilo-serving-runtime-'));fs.chmodSync(tmp,0o700);
  stageServer({repoRoot:ROOT,tmpDir:tmp,nodeModulesDir:path.join(ROOT,'node_modules'),port,rootFiles:['server.js','skills.json','openapi.json','package.json','model_config.json'],linkDirs:['public','prompts'],copyDirs:['lib','config']});
  const input=path.join(tmp,'source');fs.mkdirSync(input);fs.mkdirSync(path.join(input,'wal'));
  const wallet='0x'+'2'.repeat(40);const keyhash=sha(KEY);
  const rows={'earnings.json':{[wallet]:{pending_balance:17,total_contributor:2,total_withdrawn:0,unassented_pending:5,by_learning:{}},null:{pending_balance:4}},'accounts.json':{owner:{id:'owner',wallet,tos_version:require('../lib/accounts').CURRENT_TOS_VERSION,accepted_at:Date.now(),api_keys:[{hash:keyhash,active:true,scope:'earnings-read',scope_version:2,label:'fixture',last_used_at:'2000-01-01'}]},missingCredits:{id:'missingCredits'}},'credits.json':{owner:{plan:'free',period_start:'2000-01-01',queries_used:9}},'purchases.jsonl':'','learnings.json':[{id:'free_fixture',title:'Synthetic free learning',content:'Synthetic only',category:'testing',price:0,status:'published',visibility:'public',contributor:wallet}],'settlements.jsonl':JSON.stringify({id:'pending_settlement',wallet,amount:1,status:'retry',retry_count:10,created_at:1})+'\n'};
  for(const [name,value]of Object.entries(rows))fs.writeFileSync(path.join(input,name),typeof value==='string'?value:JSON.stringify(value));
  const walRows=[{id:'pending',operation:'withdraw',payload:{wallet_address:wallet,amount:1,settlement_id:'pending_settlement',earnings_before:17},steps_completed:['earnings_deducted'],status:'pending',created_at:1},{id:'reversal',operation:'reverse_lot_funding',payload:{purchase_id:'unknown_purchase',account_id:'owner'},steps_completed:[],status:'pending',created_at:1}];
  for(const row of walRows)fs.writeFileSync(path.join(input,'wal',row.id+'.wal.json'),JSON.stringify(row));
  fs.writeFileSync(path.join(input,'magic_links.json'),JSON.stringify({[sha('a'.repeat(43))]:{email:'new-synthetic@example.test',expires_at:Date.now()+900000}}));
  const files={};for(const name of REQUIRED)files[name]={sha256:sha(fs.readFileSync(path.join(input,name))),kind:name.endsWith('jsonl')?'jsonl':'json'};for(const name of MISSING)files[name]={absent:true,errno:'ENOENT'};
  const names=fs.readdirSync(path.join(input,'wal')).sort();const manifest={schema_version:1,mode:'serving_unknown_history',checkpoint_id:'synthetic-serving',created_at:new Date().toISOString(),approval_ref:'synthetic-only',files,wal:{entries:names.map(name=>({name,sha256:sha(fs.readFileSync(path.join(input,'wal',name)))})),listing_sha256:digestJSON(names.map(name=>({name,sha256:sha(fs.readFileSync(path.join(input,'wal',name)))})))}};
  const operator=require('../lib/stripe-serving-operator');plan=operator.createServingPlan({inputDir:input,manifest,candidateSha:'a'.repeat(40)});fs.rmSync(path.join(tmp,'data'),{recursive:true});dir=path.join(tmp,'data');operator.rehearseServing({inputDir:input,outputDir:dir,plan});
  beforeBytes=originals(dir);
  fs.writeFileSync(path.join(tmp,'deny-network.cjs'),`const fs=require('fs');const path=require('path');const deny=(...args)=>{fs.appendFileSync(path.join(__dirname,'network-attempts.log'),JSON.stringify({url:String(args[0] && (args[0].hostname || args[0].host) || args[0]),rpc:args[1]?.body?JSON.parse(args[1].body).method:null})+'\\n');throw Error('SYNTHETIC_NETWORK_DENIED');};require('http').request=deny;require('http').get=deny;require('https').request=deny;require('https').get=deny;global.fetch=deny;const actualOpen=fs.openSync,actualClose=fs.closeSync,actualSync=fs.fsyncSync;const descriptors=new Map();fs.openSync=function(file,...args){const fd=actualOpen.call(fs,file,...args);descriptors.set(fd,String(file));return fd;};fs.closeSync=function(fd){descriptors.delete(fd);return actualClose.call(fs,fd);};fs.fsyncSync=function(fd){if(fs.existsSync(path.join(__dirname,'fail-capture-fsync'))&&(descriptors.get(fd)||'').includes('stripe-quarantined-events.json'))throw Error('SYNTHETIC_CAPTURE_FSYNC_FAILURE');return actualSync.call(fs,fd);};`);
  env={NODE_ENV:'test',NODE_OPTIONS:'--require='+path.join(tmp,'deny-network.cjs'),HOME:tmp,AUXILO_HOME:tmp,AUXILO_DATA_DIR:dir,AUXILO_WAL_DIR:path.join(dir,'wal'),AUXILO_ACCOUNTS_FILE:path.join(dir,'accounts.json'),AUXILO_CREDITS_FILE:path.join(dir,'credits.json'),AUXILO_PURCHASES_FILE:path.join(dir,'purchases.jsonl'),WALLET_PRIVATE_KEY:'0x'+'11'.repeat(32),SESSION_SECRET:secret,LLM_SENSITIVITY_ENABLED:'false',PAYMENTS_ENABLED:'true',CUSTODIAL_WITHDRAW_ENABLED:'true',STRIPE_SECRET_KEY:'sk_test_'+'a'.repeat(32),STRIPE_WEBHOOK_SECRET:whLegacy,STRIPE_AUXILO_LLC_SECRET_KEY:'sk_test_'+'b'.repeat(32),STRIPE_AUXILO_LLC_WEBHOOK_SECRET:whNew};
  boot=await bootServer({tmpDir:tmp,port,env,maxAttempts:1,timeoutMs:15000});assert.ok(boot.child);
 });
 after(async()=>{if(boot)await stopServer(boot.child);if(tmp)fs.rmSync(tmp,{recursive:true,force:true});});
 test('health readiness and free catalog remain available with payment flags ON',async()=>{for(const p of ['/health','/ready','/stats','/categories','/skill/fixture']){const r=await fetch(boot.baseUrl+p,{headers:{'X-API-Key':KEY}});assert.ok([200,404].includes(r.status),p+':'+r.status);if(p==='/health')assert.equal((await r.json()).payments_enabled,false);}const discovery=await fetch(boot.baseUrl+'/discover',{method:'POST',headers:{'Content-Type':'application/json','X-API-Key':KEY},body:JSON.stringify({query:'test'})});assert.equal(discovery.status,200);const search=await fetch(boot.baseUrl+'/knowledge',{method:'POST',headers:{'Content-Type':'application/json','X-API-Key':KEY},body:JSON.stringify({query:'no-match-synthetic'})});assert.equal(search.status,200);assert.deepEqual(originals(dir),beforeBytes);});
 test('unsafe methods and every payment rail refuse before auth or writes',async()=>{for(const p of ['/checkout/session','/account/connect-stripe','/account/withdraw-stripe','/withdraw','/account/link-wallet','/register','/learn','/referral/track']){const r=await fetch(boot.baseUrl+p,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});assert.equal(r.status,503,p);assert.equal((await r.json()).code,'HISTORICAL_COVERAGE_UNKNOWN');}for(const method of ['PUT','PATCH','DELETE'])assert.equal((await fetch(boot.baseUrl+'/account/settings',{method})).status,503);assert.deepEqual(originals(dir),beforeBytes);});
 test('mutating GET credits and account bookkeeping are held',async()=>{for(const p of ['/account/credits','/auth/verify?token='+('a'.repeat(43)),'/referral/link']){const r=await fetch(boot.baseUrl+p);assert.equal(r.status,503,p);}await fetch(boot.baseUrl+'/skill/fixture',{headers:{'X-API-Key':KEY}});const earningsRead=await fetch(boot.baseUrl+'/account/earnings',{headers:{'X-API-Key':KEY}});assert.equal(earningsRead.status,200);const earningsBody=await earningsRead.json();assert.equal(earningsBody.can_withdraw,false);assert.equal(earningsBody.payouts_paused,true);assert.deepEqual(originals(dir),beforeBytes);});
 test('both signed platform routes and legacy alias capture without acknowledging processing',async()=>{for(const [p,hook,id]of [['/webhook/stripe',whLegacy,'evt_legacy'],['/webhook/stripe/legacy',whLegacy,'evt_legacy'],['/webhook/stripe/auxilo_llc',whNew,'evt_new']]){const raw=JSON.stringify(event(id));const r=await fetch(boot.baseUrl+p,{method:'POST',headers:{'stripe-signature':signed(raw,hook)},body:raw});assert.equal(r.status,503);const body=await r.json();assert.equal(body.processed,false);assert.equal(body.durably_recorded,true);assert.ok(!JSON.stringify(body).includes('must-not-leak'));}assert.deepEqual(originals(dir),beforeBytes);});
 test('signed bodies above the ordinary100KiB limit remain bounded and captured below512KiB',async()=>{const large=event('evt_large');large.data.object.padding='x'.repeat(300*1024);const raw=JSON.stringify(large);const r=await fetch(boot.baseUrl+'/webhook/stripe',{method:'POST',headers:{'stripe-signature':signed(raw)},body:raw});assert.equal(r.status,503);assert.equal((await r.json()).durably_recorded,true);assert.deepEqual(originals(dir),beforeBytes);});
 test('wrong signature context and streamed oversized input cannot capture',async()=>{const raw=JSON.stringify(event('evt_bad'));for(const [r,sig]of [[raw,signed(raw,whNew)],[JSON.stringify({...event('evt_connected'),account:'acct_external'}),null]]){const response=await fetch(boot.baseUrl+'/webhook/stripe',{method:'POST',headers:{'stripe-signature':sig||signed(r)},body:r});assert.equal(response.status,400);}const status=await new Promise((resolve,reject)=>{const request=http.request(boot.baseUrl+'/webhook/stripe',{method:'POST',headers:{'stripe-signature':'invalid','Transfer-Encoding':'chunked'}},r=>{r.resume();resolve(r.statusCode);});request.on('error',reject);for(let i=0;i<10;i++)request.write(Buffer.alloc(65536,32));request.end();});assert.equal(status,413);assert.deepEqual(originals(dir),beforeBytes);});
 test('concurrent signed duplicates and conflicts survive restart without financial writes',async()=>{const raw=JSON.stringify(event('evt_parallel'));const post=body=>fetch(boot.baseUrl+'/webhook/stripe',{method:'POST',headers:{'stripe-signature':signed(body)},body});const results=await Promise.all(Array.from({length:5},()=>post(raw)));for(const r of results)assert.equal((await r.json()).durably_recorded,true);const conflict=await post(JSON.stringify({...JSON.parse(raw),created:1}));assert.equal((await conflict.json()).durably_recorded,true);await stopServer(boot.child);boot=await bootServer({tmpDir:tmp,port,env,maxAttempts:1,timeoutMs:15000});const replay=await post(raw);assert.equal((await replay.json()).durably_recorded,true);assert.deepEqual(originals(dir),beforeBytes);assert.ok(!boot.getOutput().includes('must-not-leak'));});
 test('capture fsync failure returns503 without claiming durability or mutating financial bytes',async()=>{fs.writeFileSync(path.join(tmp,'fail-capture-fsync'),'synthetic');try{const raw=JSON.stringify(event('evt_disk_failure'));const response=await fetch(boot.baseUrl+'/webhook/stripe',{method:'POST',headers:{'stripe-signature':signed(raw)},body:raw});assert.equal(response.status,503);assert.equal((await response.json()).durably_recorded,false);}finally{fs.unlinkSync(path.join(tmp,'fail-capture-fsync'));}assert.deepEqual(originals(dir),beforeBytes);});
 test('no Stripe or on-chain write was attempted; diagnostic reads were network-denied',()=>{const log=fs.existsSync(path.join(tmp,'network-attempts.log'))?fs.readFileSync(path.join(tmp,'network-attempts.log'),'utf8'):'';assert.doesNotMatch(log,/stripe|eth_send|eth_sign|personal_sign/i);for(const line of log.trim().split('\n').filter(Boolean)){const row=JSON.parse(line);if(row.url.includes('mainnet.base.org'))assert.equal(row.rpc,'eth_getBalance');}assert.deepEqual(originals(dir),beforeBytes);});
});
