 'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const os=require('os');const path=require('path');const crypto=require('crypto');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'auxilo-provenance-'));process.env.AUXILO_DATA_DIR=tmp;process.env.AUXILO_CREDITS_FILE=path.join(tmp,'credits.json');process.env.AUXILO_ACCOUNT_HOLDS_FILE=path.join(tmp,'account-holds.json');
const origins=require('../lib/stripe-object-origins');const credits=require('../lib/credits');const holds=require('../lib/account-holds');const handlers=require('../lib/stripe-refund-handlers');
const legacy={stripe_platform:'legacy',stripe_platform_account_id:'acct_1TCbMe0Jj0R41QQV'};const newer={stripe_platform:'auxilo_llc',stripe_platform_account_id:'acct_1UMsxYLVAUzbAOHI'};
const ref={checkpoint_id:'synthetic',manifest_sha256:'a'.repeat(64),inventory_complete:true,approval_ref:'fixture-approval'};
const row=(ctx,id='pi_fixture')=>({...ctx,object_kind:'payment_intent',provider_id:id,account_id:'owner',evidence_ref:'synthetic-proof',first_observed_at:'2026-10-05T00:00:00Z',provenance_version:1});
function reset(){fs.writeFileSync(process.env.AUXILO_CREDITS_FILE,'{}');fs.writeFileSync(process.env.AUXILO_ACCOUNT_HOLDS_FILE,'{}');}
test('origin missing never initializes itself',()=>assert.throws(()=>origins.createOriginStore({file:path.join(tmp,'absent')}).all()));
test('origin explicit inventory initialization and immutable replay',()=>{origins.initializeOrigins(path.join(tmp,'stripe-object-origins.json'),ref);const s=origins.createOriginStore({file:path.join(tmp,'stripe-object-origins.json')});s.record(row(legacy));s.record(row(legacy));assert.equal(s.all().length,1);assert.throws(()=>s.record({...row(legacy),account_id:'other'}));});
test('equal provider IDs in two platforms are distinct and unscoped resolution ambiguous',()=>{origins.recordOrigin(row(newer));assert.equal(origins.findOrigin(legacy,'payment_intent','pi_fixture').stripe_platform,'legacy');assert.equal(origins.resolveOrigin('payment_intent','pi_fixture','owner'),null);});
test('corrupt origin store cannot become empty',()=>{const file=path.join(tmp,'corrupt');fs.writeFileSync(file,'{');assert.throws(()=>origins.createOriginStore({file}).all());});
test('platform-scoped paid lots dedupe separately and refund only selected origin',async()=>{reset();await credits.addDollarLot('owner','dollar_paid',10,{...legacy,stripe_payment_intent:'pi_shared',purchase_id:'old'});await credits.addDollarLot('owner','dollar_paid',20,{...newer,stripe_payment_intent:'pi_shared',purchase_id:'new'});await credits.addDollarLot('owner','dollar_paid',20,{...newer,stripe_payment_intent:'pi_shared',purchase_id:'new'});assert.equal(credits.loadCredits().owner.dollar_lots.length,2);await handlers.handleChargeRefunded({data:{object:{payment_intent:'pi_shared',amount_refunded:300}}},{stripeContext:legacy});assert.equal(credits.findAccountAndLotByPaymentIntent('pi_shared',legacy).lot.remaining_usd,7);assert.equal(credits.findAccountAndLotByPaymentIntent('pi_shared',newer).lot.remaining_usd,20);});
test('unmarked unknown lot never matches explicit platform',async()=>{reset();await credits.addDollarLot('owner','dollar_paid',10,{stripe_payment_intent:'pi_unknown'});assert.equal(credits.findAccountAndLotByPaymentIntent('pi_unknown',legacy),null);});
test('attested historical lot matches exact owner and platform',async()=>{reset();await credits.addDollarLot('owner','dollar_paid',10,{stripe_payment_intent:'pi_attested'});origins.recordOrigin(row(legacy,'pi_attested'));assert.equal(credits.findAccountAndLotByPaymentIntent('pi_attested',legacy).accountId,'owner');assert.equal(credits.findAccountAndLotByPaymentIntent('pi_attested',newer),null);});
test('second platform cannot replace first dispute hold or clear it',()=>{reset();const a={...legacy,payment_intent:'pi_shared',dispute_id:'dp1'};const b={...newer,payment_intent:'pi_shared',dispute_id:'dp2'};assert.equal(holds.placeDisputeHoldIfCompatible('owner',a).placed,true);const before=fs.readFileSync(process.env.AUXILO_ACCOUNT_HOLDS_FILE,'utf8');assert.equal(holds.placeDisputeHoldIfCompatible('owner',b).conflict,true);assert.equal(holds.clearDisputeHoldIfMatches('owner',b),false);assert.equal(fs.readFileSync(process.env.AUXILO_ACCOUNT_HOLDS_FILE,'utf8'),before);assert.equal(holds.clearDisputeHoldIfMatches('owner',a),true);});
test('unknown historical and cap holds survive scoped placement and clearance',()=>{reset();for(const reason of ['cap_overage','dispute_hold']){holds.holdAccount('owner',reason,{payment_intent:'pi_shared'});assert.equal(holds.placeDisputeHoldIfCompatible('owner',{...legacy,payment_intent:'pi_shared'}).conflict,true);assert.equal(holds.clearDisputeHoldIfMatches('owner',{...legacy,payment_intent:'pi_shared'}),false);}});
test('changed dispute ID and changed hold reason never clear',()=>{reset();holds.placeDisputeHoldIfCompatible('owner',{...legacy,payment_intent:'pi_shared',dispute_id:'dp_new'});assert.equal(holds.clearDisputeHoldIfMatches('owner',{...legacy,payment_intent:'pi_shared',dispute_id:'dp_old'}),false);holds.holdAccount('owner','cap_overage');assert.equal(holds.clearDisputeHoldIfMatches('owner',{...legacy,payment_intent:'pi_shared',dispute_id:'dp_new'}),false);});
test('both platform dispute closures preserve the other hold',async()=>{for(const [first,second]of[[legacy,newer],[newer,legacy]]){reset();for(const c of[first,second]){await credits.addDollarLot('owner','dollar_paid',10,{...c,stripe_payment_intent:'pi_hold'});await credits.removeDollarLotRemainder('owner','pi_hold',6,c);}const event=(id,status)=>({data:{object:{id,payment_intent:'pi_hold',status}}});await handlers.handleDisputeCreated(event('dp_first','needs_response'),{stripeContext:first});await handlers.handleDisputeCreated(event('dp_second','needs_response'),{stripeContext:second});await handlers.handleDisputeClosed(event('dp_second','won'),{stripeContext:second});assert.equal(holds.getAccountHold('owner').detail.stripe_platform,first.stripe_platform);await handlers.handleDisputeClosed(event('dp_first','won'),{stripeContext:first});assert.equal(holds.getAccountHold('owner'),null);}});

test('ambiguous unmarked lot cannot match either attested platform',async()=>{reset();await credits.addDollarLot('owner','dollar_paid',10,{stripe_payment_intent:'pi_fixture'});assert.equal(credits.findAccountAndLotByPaymentIntent('pi_fixture',legacy),null);assert.equal(credits.findAccountAndLotByPaymentIntent('pi_fixture',newer),null);});
