'use strict';const{test}=require('node:test');const assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto');const sha=b=>crypto.createHash('sha256').update(b).digest('hex');const serving=require('../lib/stripe-serving-operator');const coverage=require('../lib/stripe-history-coverage');
function fixture(t){const base=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'serving-unknown-'));t.after(()=>fs.rmSync(base,{recursive:true,force:true}));const inputDir=path.join(base,'in'),outputDir=path.join(base,'out');fs.mkdirSync(inputDir);fs.mkdirSync(path.join(inputDir,'wal'));const files={};for(const[name,value]of Object.entries({'earnings.json':{unknown:{pending_balance:0.7}},'accounts.json':{},'credits.json':{unknown:{query_credits:400,unlock_credits:80}},'purchases.jsonl':''})){const bytes=typeof value==='string'?value:JSON.stringify(value);fs.writeFileSync(path.join(inputDir,name),bytes);files[name]={sha256:sha(bytes),kind:name.endsWith('jsonl')?'jsonl':'json'};}for(const name of ['withdrawals.jsonl','account-holds.json','checkout-sessions.json','stripe-transfer-attempts.json'])files[name]={absent:true,errno:'ENOENT'};const manifest={schema_version:1,mode:'serving_unknown_history',checkpoint_id:'synthetic-unknown',created_at:'2026-10-06T00:00:00Z',approval_ref:'synthetic-only',files,wal:{entries:[],listing_sha256:sha('[]')}};return{base,inputDir,outputDir,manifest,candidateSha:'a'.repeat(40)};}

function arm(t){const f=fixture(t);const plan=serving.createServingPlan(f);serving.rehearseServing({...f,plan});const old=process.env.AUXILO_DATA_DIR;process.env.AUXILO_DATA_DIR=f.outputDir;t.after(()=>{if(old===undefined)delete process.env.AUXILO_DATA_DIR;else process.env.AUXILO_DATA_DIR=old;});return{...f,plan};}
function event(id='evt_synthetic'){return{id,type:'checkout.session.completed',livemode:true,data:{object:{id:'cs_synthetic',livemode:true}}};}const context={stripe_platform:'legacy',stripe_platform_account_id:require('../lib/stripe-object-origins').PLATFORMS.legacy,livemode:true};
test('no artifact means no overlay and no file creation',t=>{const f=fixture(t);assert.equal(coverage.inspectHistoryCoverage({dir:f.inputDir}).present,false);});
test('orphan coverage file or staging artifact prevents legacy fallback',t=>{for(const name of ['stripe-history-coverage.json','stripe-quarantine-recovery.orphan','stripe-quarantined-events.json.operator-'+ 'a'.repeat(64)+'.tmp']){const f=fixture(t);fs.writeFileSync(path.join(f.inputDir,name),'{}');const state=coverage.inspectHistoryCoverage({dir:f.inputDir});assert.equal(state.present,true);assert.equal(state.ready,false);}});
test('completed coverage is explicitly unknown and financial mutations blocked',t=>{arm(t);assert.equal(coverage.historyFinancialBlocked(),true);const c=coverage.assertHistoryCoverageBoot();assert.equal(c.active,true);assert.equal(c.coverage.historical_coverage,'unknown');assert.equal(c.coverage.financial_mutations_allowed,false);});
test('verified raw events durably dedupe across fresh module reload',t=>{const f=arm(t),e=event(),rawBody=JSON.stringify(e);assert.equal(coverage.captureVerifiedEvent({rawBody,event:e,context}).durably_recorded,true);assert.equal(coverage.captureVerifiedEvent({rawBody,event:e,context}).duplicate,true);delete require.cache[require.resolve('../lib/stripe-history-coverage')];const fresh=require('../lib/stripe-history-coverage');assert.equal(fresh.captureVerifiedEvent({rawBody,event:e,context}).duplicate,true);const store=fresh.exportQuarantinedEvents({dir:f.outputDir});assert.equal(store.records.length,1);assert.equal(store.records[0].raw_body,rawBody);});
test('conflicting signed digest is retained without replacing original',t=>{const f=arm(t),first=event();coverage.captureVerifiedEvent({rawBody:JSON.stringify(first),event:first,context});const changed={...first,type:'charge.refunded'};const result=coverage.captureVerifiedEvent({rawBody:JSON.stringify(changed),event:changed,context});assert.equal(result.conflict,true);const rows=coverage.exportQuarantinedEvents({dir:f.outputDir}).records;assert.equal(rows.length,2);assert.equal(rows[0].event_type,first.type);serving.recoverServingRehearsal({...f,plan:f.plan});assert.equal(coverage.exportQuarantinedEvents({dir:f.outputDir}).records.length,2);});
for(const bad of ['context','differentraw','oversize','connected'])test('capture rejects '+bad+' before durability claim',t=>{arm(t);const e=event();let rawBody=JSON.stringify(e),c=context;if(bad==='context')c={...context,stripe_platform_account_id:'acct_wrong'};if(bad==='differentraw')rawBody=JSON.stringify({...e,type:'other'});if(bad==='oversize')rawBody=' '.repeat(512*1024+1);if(bad==='connected'){e.account='acct_external';rawBody=JSON.stringify(e);}assert.throws(()=>coverage.captureVerifiedEvent({rawBody,event:e,context:c}));});
test('fsync failure does not acknowledge a durable event',t=>{arm(t);const e=event(),original=fs.fsyncSync;fs.fsyncSync=()=>{throw Error('synthetic fsync failure');};try{assert.throws(()=>coverage.captureVerifiedEvent({rawBody:JSON.stringify(e),event:e,context}));}finally{fs.fsyncSync=original;}});
test('coverage status contains no raw event payload',t=>{const f=arm(t),e=event();e.secret_synthetic='DO_NOT_LEAK';coverage.captureVerifiedEvent({rawBody:JSON.stringify(e),event:e,context});assert.equal(JSON.stringify(coverage.inspectHistoryCoverage({dir:f.outputDir})).includes('DO_NOT_LEAK'),false);});

test('inconclusive directory read fails closed instead of legacy fallback',t=>{const f=fixture(t),original=fs.readdirSync;fs.readdirSync=(file,...args)=>{if(file===f.inputDir){const e=Error('denied');e.code='EACCES';throw e;}return original(file,...args);};try{const result=coverage.inspectHistoryCoverage({dir:f.inputDir});assert.equal(result.present,true);assert.equal(result.ready,false);}finally{fs.readdirSync=original;}});
test('journal must bind initial capture checksum',t=>{const f=arm(t),file=path.join(f.outputDir,coverage.JOURNAL);const j=JSON.parse(fs.readFileSync(file));j.capture_initial_checksum='a'.repeat(64);fs.writeFileSync(file,JSON.stringify(coverage.seal(j)));assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).ready,false);});
test('16MiB capture quota retains all prior records and still dedupes without growth',t=>{const f=arm(t),e=event();e.padding='x'.repeat(500000);coverage.captureVerifiedEvent({rawBody:JSON.stringify(e),event:e,context});const file=path.join(f.outputDir,coverage.CAPTURE),store=JSON.parse(fs.readFileSync(file)),template=store.records[0],{digestJSON}=require('../lib/stripe-transfer-persistence');let head=template.previous_hash;store.records=[];for(let i=0;i<33;i++){const ev={...e,id:'evt_quota_'+i},raw=JSON.stringify(ev),row={...template,sequence:i+1,previous_hash:head,event_id:ev.id,raw_body:raw,raw_digest:sha(raw),conflict:false};delete row.record_hash;row.record_hash=digestJSON(row);store.records.push(row);head=row.record_hash;}store.head_hash=head;fs.writeFileSync(file,JSON.stringify(coverage.seal(store)));const before=fs.readFileSync(file);assert(before.length<16*1024*1024);const newEvent={...e,id:'evt_overflow'};assert.throws(()=>coverage.captureVerifiedEvent({rawBody:JSON.stringify(newEvent),event:newEvent,context}),err=>err.code==='QUARANTINE_CAPACITY_REACHED');assert.deepEqual(fs.readFileSync(file),before);const dup=JSON.parse(store.records[0].raw_body);assert.equal(coverage.captureVerifiedEvent({rawBody:store.records[0].raw_body,event:dup,context}).duplicate,true);assert.deepEqual(fs.readFileSync(file),before);});

test('actual SIGKILL during capture requires explicit forward recovery and preserves record',t=>{const f=arm(t),pf=path.join(f.base,'saved-plan.json');fs.writeFileSync(pf,JSON.stringify(f.plan));const child=require('child_process').spawnSync(process.execPath,['-e',`const fs=require('fs');const original=fs.renameSync;fs.renameSync=(a,b)=>{if(a.includes('.capture-'))process.kill(process.pid,'SIGKILL');return original(a,b)};const h=require(${JSON.stringify(require.resolve('../lib/stripe-history-coverage'))});const e=${JSON.stringify(event('evt_killed'))};h.captureVerifiedEvent({rawBody:JSON.stringify(e),event:e,context:${JSON.stringify(context)}});`],{env:{...process.env,AUXILO_DATA_DIR:f.outputDir}});assert.equal(child.signal,'SIGKILL');assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).ready,false);assert.throws(()=>serving.recoverServingRehearsal({...f,plan:f.plan}));assert.equal(serving.recoverServingRehearsal({...f,plan:f.plan,allowCaptureRecovery:true}).state,'capture_recovered');assert.equal(coverage.exportQuarantinedEvents({dir:f.outputDir}).records[0].event_id,'evt_killed');assert.equal(serving.recoverServingRehearsal({...f,plan:f.plan,allowCaptureRecovery:true}).state,'completed_verified');});
test('truncated capture stage is archived exactly before cleanup and recovery is idempotent',t=>{const f=arm(t),stage=path.join(f.outputDir,coverage.CAPTURE+'.capture-'+f.plan.checksum+'.tmp'),raw=Buffer.from('{"truncated":');fs.writeFileSync(stage,raw,{mode:0o600});const pf=path.join(f.base,'recovery-plan.json');fs.writeFileSync(pf,JSON.stringify(f.plan));const child=require('child_process').spawnSync(process.execPath,['-e',`const s=require(${JSON.stringify(require.resolve('../lib/stripe-serving-operator'))});s.recoverServingRehearsal({inputDir:${JSON.stringify(f.inputDir)},outputDir:${JSON.stringify(f.outputDir)},plan:require(${JSON.stringify(pf)}),allowCaptureRecovery:true,afterWrite:name=>{if(name==='capture-recovery-archived')process.kill(process.pid,'SIGKILL')}});`]);assert.equal(child.signal,'SIGKILL');assert.deepEqual(fs.readFileSync(stage),raw);assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).ready,false);assert.equal(serving.recoverServingRehearsal({...f,plan:f.plan,allowCaptureRecovery:true}).state,'capture_recovered');const archiveDir=path.join(f.outputDir,'stripe-quarantine-recovery'),names=fs.readdirSync(archiveDir);assert.deepEqual(names,[sha(raw)+'.json']);const archive=JSON.parse(fs.readFileSync(path.join(archiveDir,names[0])));assert.equal(archive.status,'unapplied_recovery_evidence');assert.deepEqual(Buffer.from(archive.raw_stage_base64,'base64'),raw);assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).active,true);assert.equal(serving.recoverServingRehearsal({...f,plan:f.plan,allowCaptureRecovery:true}).state,'completed_verified');});
test('archive orphan and symlink never allow legacy fallback or evidence replacement',t=>{const f=fixture(t),archive=path.join(f.inputDir,'stripe-quarantine-recovery');fs.mkdirSync(archive);assert.equal(coverage.inspectHistoryCoverage({dir:f.inputDir}).ready,false);const armed=arm(t),stage=path.join(armed.outputDir,coverage.CAPTURE+'.capture-'+armed.plan.checksum+'.tmp');fs.symlinkSync(path.join(armed.outputDir,'credits.json'),stage);assert.throws(()=>serving.recoverServingRehearsal({...armed,plan:armed.plan,allowCaptureRecovery:true}));});

test('every normal migration artifact conflicts with completed serving coverage',t=>{const f=arm(t);for(const name of ['stripe-migration-journal.json','stripe-migration-control.json','stripe-migration-armed.json','stripe-object-origins.json','stripe-checkout-intents.json','stripe-event-receipts.json','stripe-connect-intents.json']){const file=path.join(f.outputDir,name);fs.writeFileSync(file,'{}');assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).ready,false,name);fs.unlinkSync(file);}assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).active,true);});
