'use strict';const{test}=require('node:test');const assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),crypto=require('crypto');const sha=b=>crypto.createHash('sha256').update(b).digest('hex');const serving=require('../lib/stripe-serving-operator');const coverage=require('../lib/stripe-history-coverage');
function fixture(t){const base=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'serving-unknown-'));t.after(()=>fs.rmSync(base,{recursive:true,force:true}));const inputDir=path.join(base,'in'),outputDir=path.join(base,'out');fs.mkdirSync(inputDir);fs.mkdirSync(path.join(inputDir,'wal'));const files={};for(const[name,value]of Object.entries({'earnings.json':{unknown:{pending_balance:0.7}},'accounts.json':{},'credits.json':{unknown:{query_credits:400,unlock_credits:80}},'purchases.jsonl':''})){const bytes=typeof value==='string'?value:JSON.stringify(value);fs.writeFileSync(path.join(inputDir,name),bytes);files[name]={sha256:sha(bytes),kind:name.endsWith('jsonl')?'jsonl':'json'};}for(const name of ['withdrawals.jsonl','account-holds.json','checkout-sessions.json','stripe-transfer-attempts.json'])files[name]={absent:true,errno:'ENOENT'};const manifest={schema_version:1,mode:'serving_unknown_history',checkpoint_id:'synthetic-unknown',created_at:'2026-10-06T00:00:00Z',approval_ref:'synthetic-only',files,wal:{entries:[],listing_sha256:sha('[]')}};return{base,inputDir,outputDir,manifest,candidateSha:'a'.repeat(40)};}

test('typed serving plan retains all financial bytes and four explicit absences',t=>{const f=fixture(t),plan=serving.createServingPlan(f);assert.equal(plan.mode,'serving_unknown_history');assert.equal(plan.historical_coverage,'unknown');assert.equal(plan.financial_mutations_allowed,false);assert.equal(plan.source.absent_names.length,4);serving.rehearseServing({...f,plan});for(const[name,row]of Object.entries(f.manifest.files)){const target=path.join(f.outputDir,name);if(row.absent)assert.equal(fs.existsSync(target),false);else assert.equal(sha(fs.readFileSync(target)),row.sha256);}assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).active,true);});
for(const defect of ['missing-core','unattested-absence','corrupt-json','corrupt-jsonl','invalid-present-d0','symlink'])test('serving plan refuses '+defect,t=>{const f=fixture(t);if(defect==='missing-core')fs.unlinkSync(path.join(f.inputDir,'earnings.json'));if(defect==='unattested-absence')delete f.manifest.files['withdrawals.jsonl'];if(defect==='corrupt-json'){fs.writeFileSync(path.join(f.inputDir,'credits.json'),'{');f.manifest.files['credits.json'].sha256=sha('{');}if(defect==='corrupt-jsonl'){fs.writeFileSync(path.join(f.inputDir,'purchases.jsonl'),'{}');f.manifest.files['purchases.jsonl'].sha256=sha('{}');}if(defect==='invalid-present-d0'){fs.writeFileSync(path.join(f.inputDir,'stripe-transfer-attempts.json'),'{}');f.manifest.files['stripe-transfer-attempts.json']={kind:'json',sha256:sha('{}')};}if(defect==='symlink'){fs.unlinkSync(path.join(f.inputDir,'credits.json'));fs.symlinkSync(path.join(f.inputDir,'accounts.json'),path.join(f.inputDir,'credits.json'));}assert.throws(()=>serving.createServingPlan(f));});
test('normal operator never admits unknown-history plan',t=>{const f=fixture(t),plan=serving.createServingPlan(f);assert.throws(()=>require('../lib/stripe-production-operator').validateOperatorPlan(plan));});
test('source appearance or changed byte prevents rehearsal',t=>{const f=fixture(t),plan=serving.createServingPlan(f);fs.writeFileSync(path.join(f.inputDir,'withdrawals.jsonl'),'');assert.throws(()=>serving.rehearseServing({...f,plan}));assert.equal(fs.existsSync(f.outputDir),false);});
test('production maintains actual identity gates without injected runtime',t=>{const f=fixture(t),plan=serving.createServingPlan(f);assert.throws(()=>serving.maintainServing({targetDir:f.inputDir,plan,approval:{}}));assert.throws(()=>serving.maintainServing({targetDir:f.inputDir,plan,approval:{},runtime:{platform:'linux'}}));});
test('private overlay permissions and partial states stay unavailable',t=>{const f=fixture(t),plan=serving.createServingPlan(f);assert.throws(()=>serving.rehearseServing({...f,plan,afterWrite:name=>{if(name==='stripe-history-coverage.json')throw Error('crash');}}));assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).ready,false);serving.recoverServingRehearsal({...f,plan});assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).active,true);assert.equal(fs.statSync(f.outputDir).mode&0o777,0o700);for(const name of coverage.ARTIFACTS)assert.equal(fs.statSync(path.join(f.outputDir,name)).mode&0o777,0o600);});
test('real SIGKILL at every durable overlay boundary recovers only forward',t=>{const{spawnSync}=require('child_process');for(const point of ['stripe-history-coverage-journal.json','stripe-quarantined-events.json','stripe-history-coverage.json','journal-completed']){const f=fixture(t),plan=serving.createServingPlan(f),pf=path.join(f.base,'plan.json');fs.writeFileSync(pf,JSON.stringify(plan));const script=`const s=require(${JSON.stringify(require.resolve('../lib/stripe-serving-operator'))});s.rehearseServing({inputDir:${JSON.stringify(f.inputDir)},outputDir:${JSON.stringify(f.outputDir)},plan:require(${JSON.stringify(pf)}),afterWrite:n=>{if(n===${JSON.stringify(point)})process.kill(process.pid,'SIGKILL')}})`;const child=spawnSync(process.execPath,['-e',script]);assert.equal(child.signal,'SIGKILL');if(point!=='journal-completed')assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).ready,false);serving.recoverServingRehearsal({...f,plan});assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).active,true);}});
test('persisted CLI plan and rehearsal/recovery use typed modes',t=>{const f=fixture(t),mf=path.join(f.base,'manifest.json'),pf=path.join(f.base,'plan.json');fs.writeFileSync(mf,JSON.stringify(f.manifest));const{main}=require('../scripts/stripe-production-operator');const out=main(['--mode','serving-plan','--input',f.inputDir,'--manifest',mf,'--candidate-sha',f.candidateSha,'--output',pf]);assert.equal(out.mode,'serving_unknown_history');assert.equal(main(['--mode','serving-rehearse','--input',f.inputDir,'--output',f.outputDir,'--plan',pf]).state,'completed');assert.equal(main(['--mode','serving-recover-rehearsal','--input',f.inputDir,'--output',f.outputDir,'--plan',pf]).state,'completed_verified');});
test('unrelated recovery output and missing original refuse',t=>{const f=fixture(t),plan=serving.createServingPlan(f);serving.rehearseServing({...f,plan});fs.unlinkSync(path.join(f.outputDir,'earnings.json'));assert.throws(()=>serving.recoverServingRehearsal({...f,plan}));});

test('completed recovery permits new nonfinancial files and never rewrites overlay',t=>{const f=fixture(t),plan=serving.createServingPlan(f);serving.rehearseServing({...f,plan});const before=Object.fromEntries(coverage.ARTIFACTS.map(n=>[n,{bytes:fs.readFileSync(path.join(f.outputDir,n)),mtime:fs.statSync(path.join(f.outputDir,n)).mtimeMs}]));fs.writeFileSync(path.join(f.outputDir,'query-telemetry.json'),'[]');assert.equal(serving.recoverServingRehearsal({...f,plan}).state,'completed_verified');for(const[n,v]of Object.entries(before)){assert.deepEqual(fs.readFileSync(path.join(f.outputDir,n)),v.bytes);assert.equal(fs.statSync(path.join(f.outputDir,n)).mtimeMs,v.mtime);}fs.writeFileSync(path.join(f.outputDir,'credits.json'),'{}');assert.throws(()=>serving.recoverServingRehearsal({...f,plan}));});
test('nonfinancial array fixtures remain valid through plan validation',t=>{const f=fixture(t);fs.writeFileSync(path.join(f.inputDir,'learnings.json'),'[]');const plan=serving.createServingPlan(f);serving.rehearseServing({...f,plan});assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).active,true);});
test('sealed plan cannot disconnect captured bytes from manifest evidence',t=>{const f=fixture(t),plan=serving.createServingPlan(f),p=require('../lib/stripe-production-operator').privatePrimitives;plan.source.files['credits.json']={sha256:sha('{}'),bytes_base64:Buffer.from('{}').toString('base64')};plan.source_fingerprint=require('../lib/stripe-transfer-persistence').digestJSON(plan.source);assert.throws(()=>serving.validateServingPlan(p.seal(plan)));});
test('capture metadata records full production listing without inventing unrelated bytes',t=>{const f=fixture(t);const before={};for(const[n,row]of Object.entries(f.manifest.files))before[n]=row.absent?{state:'absent',errno:'ENOENT'}:{state:'present',sha256:row.sha256};const listing=[...Object.keys(before).filter(n=>before[n].state==='present'),'wal','lost+found','unexported-catalog.json'].map(name=>({name,state:'present',type:['wal','lost+found'].includes(name)?'directory':'file'}));f.manifest.capture={stable:true,read_only:true,source_root:'/app/data',before,after:before,wal_before:{listing:[]},wal_after:{listing:[]},top_level_metadata:listing,errors:[]};const plan=serving.createServingPlan(f);assert.equal(plan.source.original_names.includes('unexported-catalog.json'),true);serving.rehearseServing({...f,plan});assert.equal(fs.existsSync(path.join(f.outputDir,'unexported-catalog.json')),false);assert.equal(serving.recoverServingRehearsal({...f,plan}).state,'completed_verified');});

test('historical empty settlement lines and reservation arrays retain exact observed bytes',t=>{const f=fixture(t);for(const[name,bytes]of Object.entries({'settlements.jsonl':'\n','reservations.json':'[]\n'})){fs.writeFileSync(path.join(f.inputDir,name),bytes);f.manifest.files[name]={sha256:sha(bytes)};}const plan=serving.createServingPlan(f);serving.rehearseServing({...f,plan});for(const name of ['settlements.jsonl','reservations.json'])assert.deepEqual(fs.readFileSync(path.join(f.inputDir,name)),fs.readFileSync(path.join(f.outputDir,name)));assert.equal(coverage.inspectHistoryCoverage({dir:f.outputDir}).active,true);});

test('only an exact empty root-interrupted private archive directory permits ownership completion',()=>{const stat={mode:0o40700,uid:0,gid:0,isDirectory:()=>true,isSymbolicLink:()=>false},owner={uid:1000,gid:1000},operator={uid:0,gid:0};assert.equal(serving.validateInterruptedArchiveOwnership({stat,owner,operator,entries:[]}),true);for(const change of [{entries:['evidence.json']},{operator:{uid:501,gid:20}},{stat:{...stat,uid:501}},{stat:{...stat,mode:0o40755}},{stat:{...stat,isSymbolicLink:()=>true}},{stat:{...stat,isDirectory:()=>false}}])assert.throws(()=>serving.validateInterruptedArchiveOwnership({stat,owner,operator,entries:[],...change}));});
