'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const controls=require('../lib/stripe-migration-controls');
const assignments=require('../lib/stripe-payout-assignments');
const {digestJSON}=require('../lib/stripe-transfer-persistence');
const ref={checkpoint_id:'cp-test',manifest_sha256:'a'.repeat(64),inventory_complete:true,approval_ref:'approval-test'};
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'migration-controls-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return{file:path.join(dir,'control.json'),armedFile:path.join(dir,'armed.json'),journalFile:path.join(dir,'journal.json'),checkoutFile:path.join(dir,'checkout.json'),eventsFile:path.join(dir,'events.json'),originsFile:path.join(dir,'origins.json')};}
function fixture(){return{schema_version:1,revision:1,checkpoint_id:'cp-test',checkpoint_at:'2026-01-01T00:00:00Z',source_hashes:{earnings:'a'.repeat(64)},earnings_key:'owner',account_id:'owner',local_owner_resolved:true,amount_usd:10,currency:'usd',unit_precision:2,assent_status:'accepted',assent_evidence_ref:'terms',obligation_origin:'legacy',obligation_entity:'legacy entity',transaction_refs:['verified-live-charge'],stripe_platform:'legacy',stripe_platform_account_id:'acct_1TCbMe0Jj0R41QQV',livemode:true,stripe_connect_id:'acct_builder',destination_verified:true,capability_evidence_ref:'capability',servicing_evidence_ref:'servicing',servicing_effective_at:'2026-01-01T00:00:00Z',ledger_balance_usd:10,unresolved_attempts:0,holds:[],reserved_cents:0,available_cents:1000,pending_cents:0,restricted_cents:0,cash_checkpoint_at:'2026-01-01T00:00:00Z',gross_amount_cents:1000,net_amount_cents:900,fee_cents:100,disposition:'approved',reason:'evidenced',money_pm_approval_revision:1,execution_approval_ref:'exec'};}
function current(e){return{accountId:e.account_id,earningsKey:e.earnings_key,context:{stripe_platform:e.stripe_platform,stripe_platform_account_id:e.stripe_platform_account_id,livemode:e.livemode},mapping:{stripe_connect_id:e.stripe_connect_id},amountUsd:10,netCents:900,availableCents:1000,reservedCents:0,assent:true,currentLedgerBalance:10,checkpointId:e.checkpoint_id,approvalRevision:1,executionApprovalRef:'exec',unknownAttempts:false,holds:[]};}
test('unarmed compatibility does not synthesize an initialized store',t=>{const opts=temp(t),c=controls.getMigrationControl(opts);assert.equal(c.armed,false);assert.equal(c.intake_platform,'legacy');assert.equal(c.allow_checkout,true);assert.equal(fs.existsSync(opts.file),false);});
test('marker without control/journal fails closed',t=>{const opts=temp(t);fs.writeFileSync(opts.armedFile,JSON.stringify(ref));assert.equal(controls.getMigrationControl(opts).ready,false);assert.throws(()=>controls.assertActionAllowed('checkout',opts));});
test('incomplete journal fails financial guard even before arming',t=>{const opts=temp(t);fs.writeFileSync(opts.journalFile,JSON.stringify({state:'applying'}));assert.equal(controls.getMigrationControl(opts).ready,false);});
test('unknown action cannot silently bypass controls',t=>{assert.throws(()=>controls.assertActionAllowed('typo',temp(t)));});
test('funded evidenced legacy assignment admits existing flow',()=>{const e=fixture();assert.equal(assignments.validatePayoutAssignment(e,current(e)),e);});
for(const [name,patch,live]of[
 ['zero available cash',{}, {availableCents:0}],['unmapped owner',{local_owner_resolved:false},{}],['unknown origin',{obligation_origin:null},{}],['unknown destination',{stripe_connect_id:null},{}],['unsupported mixed origin',{obligation_origin:'mixed'},{}],['test cash cannot back live',{livemode:false},{context:{stripe_platform:'legacy',stripe_platform_account_id:'acct_1TCbMe0Jj0R41QQV',livemode:true}}],['stale revision',{}, {approvalRevision:2}],['unknown attempt',{}, {unknownAttempts:true}],['reservation conflict',{}, {reservedCents:101}],['disabled disposition',{disposition:'disabled'},{}],['missing evidence',{servicing_evidence_ref:null},{}]
])test('assignment refuses '+name,()=>{const e={...fixture(),...patch};assert.throws(()=>assignments.validatePayoutAssignment(e,{...current(e),...live}));});
test('LLC intake never rewrites legacy assignment source',()=>{const e=fixture();assert.equal(assignments.validatePayoutAssignment(e,{...current(e),intake_platform:'auxilo_llc'}).stripe_platform,'legacy');});
test('independent evidenced LLC assignment may qualify',()=>{const e={...fixture(),stripe_platform:'auxilo_llc',stripe_platform_account_id:'acct_1UMsxYLVAUzbAOHI',obligation_origin:'auxilo_llc'};assert.equal(assignments.validatePayoutAssignment(e,current(e)),e);});
test('assignment checksum and owner keys cannot drift',t=>{const opts=temp(t),e=fixture();fs.writeFileSync(opts.file,JSON.stringify(assignments.sealAssignments({schema_version:1,entries:{owner:e}})));assert.equal(assignments.loadPayoutAssignment('owner',opts).account_id,'owner');const x=JSON.parse(fs.readFileSync(opts.file));x.entries.owner.account_id='other';fs.writeFileSync(opts.file,JSON.stringify(x));assert.throws(()=>assignments.loadPayoutAssignment('owner',opts));});
test('per-platform admission serializes concurrent allocation',async()=>{const release=await assignments.acquirePlatformAdmissionLock('legacy');let entered=false;const wait=assignments.acquirePlatformAdmissionLock('legacy').then(r=>{entered=true;r();});await new Promise(r=>setImmediate(r));assert.equal(entered,false);release();await wait;assert.equal(entered,true);});

function armedFixture(t,phase='legacy_only'){const options=temp(t),binding={schema_version:1,checkpoint_id:ref.checkpoint_id,manifest_sha256:ref.manifest_sha256,approval_ref:ref.approval_ref,journal_id:'journal-test'};const j={...binding,state:'completed',entries:[],unknown_origin:0,hold_conflicts:0,unresolved_attempts:0};j.checksum=digestJSON(j);fs.writeFileSync(options.journalFile,JSON.stringify(j));require('../lib/stripe-checkout-intents').initializeCheckoutIntents(options.checkoutFile,ref);require('../lib/stripe-event-receipts').initializeEventReceipts(options.eventsFile,ref);require('../lib/stripe-object-origins').initializeOrigins(options.originsFile,ref);const base={phase,intake_platform:'legacy',allow_checkout:true,allow_connect_creation:true,allow_builder_transfer:true,payout_approval_revision:1,execution_approval_ref:'exec'};controls.initializeMigrationControl({...options,manifestRef:ref,journalId:'journal-test',control:base,isolatedFixture:true,approved:true});return options;}
test('armed drain blocks creations while signed event processing survives',t=>{const options=armedFixture(t);const c=controls.transitionMigrationControl(1,{phase:'draining',intake_platform:null,allow_checkout:false,allow_connect_creation:false,allow_builder_transfer:false},{...options,isolatedFixture:true,approved:true});assert.equal(c.ready,true);for(const action of ['checkout','connect_creation','builder_transfer'])assert.throws(()=>controls.assertActionAllowed(action,options));assert.equal(controls.assertActionAllowed('webhook',options).ready,true);});
test('unknown history refuses new intake; generation and binding remain fixed',t=>{const options=armedFixture(t),allow={...options,isolatedFixture:true,approved:true};assert.throws(()=>controls.transitionMigrationControl(1,{phase:'new_intake',intake_platform:'auxilo_llc',unknown_history_count:1},allow));const c=controls.transitionMigrationControl(1,{phase:'new_intake',intake_platform:'auxilo_llc',unknown_history_count:0},allow);assert.equal(c.intake_platform,'auxilo_llc');assert.throws(()=>controls.transitionMigrationControl(1,{phase:'legacy_only',intake_platform:'legacy'},allow));assert.throws(()=>controls.transitionMigrationControl(2,{checkpoint_id:'replacement'},allow));});
test('completed apply without marker is maintenance rather than unarmed compatibility',t=>{const options=armedFixture(t);fs.unlinkSync(options.armedFile);assert.equal(controls.getMigrationControl(options).ready,false);});
test('control corruption and journal mismatch fail closed',t=>{const options=armedFixture(t),marker=JSON.parse(fs.readFileSync(options.armedFile));marker.checkpoint_id='other';fs.writeFileSync(options.armedFile,JSON.stringify(marker));assert.equal(controls.getMigrationControl(options).ready,false);});
test('live assignment cannot cite test Checkout as backing',()=>{const e=fixture();e.transaction_refs=['cs_test_not_live'];assert.throws(()=>assignments.validatePayoutAssignment(e,current(e)));});
test('different destination and mixed-source assignment need own evidence',()=>{const e=fixture();assert.throws(()=>assignments.validatePayoutAssignment(e,{...current(e),mapping:{connected_id:'acct_other'}}));e.obligation_origin='auxilo_llc';assert.throws(()=>assignments.validatePayoutAssignment(e,current(e)));});

test('payout activation requires independent current approval references',t=>{const options=armedFixture(t),control=JSON.parse(fs.readFileSync(options.file));delete control.payout_approval_revision;delete control.checksum;control.checksum=digestJSON(control);fs.writeFileSync(options.file,JSON.stringify(control));assert.equal(controls.getMigrationControl(options).ready,false);});

function resealJournal(options,patch,remove){const j=JSON.parse(fs.readFileSync(options.journalFile));Object.assign(j,patch);if(remove)delete j[remove];delete j.checksum;j.checksum=digestJSON(j);fs.writeFileSync(options.journalFile,JSON.stringify(j));}
const newIntakePatch={phase:'new_intake',intake_platform:'auxilo_llc',unknown_history_count:0};
for(const counter of ['unknown_origin','hold_conflicts','unresolved_attempts'])test('caller zero cannot bypass validated journal '+counter,t=>{const options=armedFixture(t);resealJournal(options,{[counter]:1});assert.throws(()=>controls.transitionMigrationControl(1,newIntakePatch,{...options,isolatedFixture:true,approved:true}));assert.equal(controls.getMigrationControl(options).phase,'legacy_only');});
for(const counter of ['unknown_origin','hold_conflicts','unresolved_attempts'])test('missing actual journal '+counter+' is not zero',t=>{const options=armedFixture(t);resealJournal(options,{},counter);assert.throws(()=>controls.transitionMigrationControl(1,newIntakePatch,{...options,isolatedFixture:true,approved:true}));});
for(const defect of ['missing','corrupt','binding'])test('new intake requires actual initialized Checkout inventory: '+defect,t=>{const options=armedFixture(t);if(defect==='missing')fs.unlinkSync(options.checkoutFile);if(defect==='corrupt')fs.writeFileSync(options.checkoutFile,'{');if(defect==='binding'){const data=JSON.parse(fs.readFileSync(options.checkoutFile));data.initialization_manifest.checkpoint_id='other';delete data.checksum;data.checksum=digestJSON(data);fs.writeFileSync(options.checkoutFile,JSON.stringify(data));}assert.throws(()=>controls.transitionMigrationControl(1,newIntakePatch,{...options,isolatedFixture:true,approved:true}));});
function prepareIntent(options){const store=require('../lib/stripe-checkout-intents').createCheckoutIntentStore({file:options.checkoutFile});let intent=store.prepare({account_id:'customer',pack_id:'starter',currency:'usd',amount_cents:1000,base_url:'https://example.test',stripe_platform:'legacy',stripe_platform_account_id:'acct_1TCbMe0Jj0R41QQV',livemode:true,configuration_generation:'fixture'});return{store,intent};}
function evidence(intent,extra={}){return{verified:true,authoritative:true,evidence_ref:'synthetic-proof',intent_id:intent.intent_id,account_id:intent.account_id,amount_cents:intent.amount_cents,currency:'usd',session_id:'cs_fixture',stripe_platform:intent.stripe_platform,stripe_platform_account_id:intent.stripe_platform_account_id,livemode:true,...extra};}
for(const state of ['prepared','submitted','unknown','paid_pending_credit','expired_open'])test('new intake refuses durable '+state+' across all customer accounts',t=>{const options=armedFixture(t);let{store,intent}=prepareIntent(options);if(state!=='prepared')intent=store.transition(intent.intent_id,intent.generation,'submitted');if(state==='unknown')store.transition(intent.intent_id,intent.generation,'unknown');if(state==='paid_pending_credit')store.transition(intent.intent_id,intent.generation,'paid_pending_credit',{session_id:'cs_fixture',evidence:evidence(intent)});if(state==='expired_open')store.transition(intent.intent_id,intent.generation,'confirmed_open',{session_id:'cs_fixture',session_url:'https://checkout.example.test/session',expires_at:Date.now()-1,cap_state_durable:true,evidence:evidence(intent)});assert.throws(()=>controls.transitionMigrationControl(1,newIntakePatch,{...options,isolatedFixture:true,approved:true}));});
test('ongoing customer uncertainty does not stop signed events in already active new intake',t=>{const options=armedFixture(t);controls.transitionMigrationControl(1,newIntakePatch,{...options,isolatedFixture:true,approved:true});prepareIntent(options);assert.equal(controls.getMigrationControl(options).ready,true);assert.equal(controls.assertActionAllowed('webhook',options).ready,true);});
test('new intake read rechecks actual historical journal counters',t=>{const options=armedFixture(t);controls.transitionMigrationControl(1,newIntakePatch,{...options,isolatedFixture:true,approved:true});resealJournal(options,{unknown_origin:1});assert.equal(controls.getMigrationControl(options).ready,false);});
test('direct initialization cannot bypass journal history with caller zero',t=>{const options=armedFixture(t);fs.unlinkSync(options.file);fs.unlinkSync(options.armedFile);resealJournal(options,{hold_conflicts:1});assert.throws(()=>controls.initializeMigrationControl({...options,manifestRef:ref,journalId:'journal-test',control:{...newIntakePatch,allow_checkout:true,allow_connect_creation:false,allow_builder_transfer:false},isolatedFixture:true,approved:true}));assert.equal(fs.existsSync(options.file),false);});

for(const store of ['checkoutFile','eventsFile','originsFile'])for(const defect of ['missing','corrupt','binding'])test('checkout refuses '+defect+' fulfillment store '+store,t=>{const options=armedFixture(t);if(defect==='missing')fs.unlinkSync(options[store]);if(defect==='corrupt')fs.writeFileSync(options[store],'{');if(defect==='binding'){const s=JSON.parse(fs.readFileSync(options[store]));(s.manifest||s.initialization_manifest).checkpoint_id='other';delete s.checksum;s.checksum=digestJSON(s);fs.writeFileSync(options[store],JSON.stringify(s));}assert.throws(()=>controls.assertActionAllowed('checkout',options));assert.equal(controls.assertActionAllowed('webhook',options).ready,true);});
test('positive initialized fulfillment inventories admit checkout',t=>{const options=armedFixture(t);assert.equal(controls.assertActionAllowed('checkout',options).ready,true);});
test('unarmed checkout still requires same-manifest initialized fulfillment stores',t=>{const options=temp(t);assert.throws(()=>controls.assertActionAllowed('checkout',options));require('../lib/stripe-checkout-intents').initializeCheckoutIntents(options.checkoutFile,ref);require('../lib/stripe-event-receipts').initializeEventReceipts(options.eventsFile,ref);require('../lib/stripe-object-origins').initializeOrigins(options.originsFile,ref);assert.equal(controls.assertActionAllowed('checkout',options).ready,true);const origin=JSON.parse(fs.readFileSync(options.originsFile));origin.manifest.manifest_sha256='b'.repeat(64);delete origin.checksum;origin.checksum=digestJSON(origin);fs.writeFileSync(options.originsFile,JSON.stringify(origin));assert.throws(()=>controls.assertActionAllowed('checkout',options));});
