 'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const os=require('os');const path=require('path');const crypto=require('crypto');
const migration=require('../lib/stripe-migration-journal');const reconcile=require('../lib/stripe-migration-reconcile');
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function fixture(){const base=fs.mkdtempSync(path.join(os.tmpdir(),'auxilo-migration-'));const inputDir=path.join(base,'in');const outputDir=path.join(base,'out');fs.mkdirSync(inputDir);const data={'earnings.json':{owner:{pending_balance:3.15,total_earned:5}},'accounts.json':{owner:{id:'owner'}},'credits.json':{owner:{dollar_lots:[{lot_id:'lot1',kind:'dollar_paid',stripe_payment_intent:'pi1',original_usd:10,remaining_usd:7,funded_unlocks:[]},{lot_id:'promo',kind:'dollar_promo',original_usd:2,remaining_usd:2}]}},'purchases.jsonl':'','withdrawals.jsonl':'','account-holds.json':{owner:{reason:'dispute_hold',held_at:'old',detail:{payment_intent:'pi1',remaining_usd:7}}},'checkout-sessions.json':{},'stripe-transfer-attempts.json':{schema_version:1,attempts:[]}};const attemptFile=path.join(inputDir,'stripe-transfer-attempts.json');require('../lib/stripe-transfer-attempts').initializeAttemptStore(attemptFile,{sha256:'b'.repeat(64),inventory_complete:true,positive_history_attestation:true,history_interval:{start:'2026-01-01',end:'2026-10-05'},platforms:[{stripe_platform:'legacy',stripe_platform_account_id:'acct_1TCbMe0Jj0R41QQV',livemode:true},{stripe_platform:'auxilo_llc',stripe_platform_account_id:'acct_1UMsxYLVAUzbAOHI',livemode:true}]});data['stripe-transfer-attempts.json']=JSON.parse(fs.readFileSync(attemptFile));const files={};for(const[n,v]of Object.entries(data)){const bytes=typeof v==='string'?v:JSON.stringify(v);fs.writeFileSync(path.join(inputDir,n),bytes);files[n]={sha256:sha(bytes),kind:n.endsWith('jsonl')?'jsonl':'json'};}fs.mkdirSync(path.join(inputDir,'wal'));const mapping={stripe_platform:'legacy',stripe_platform_account_id:'acct_1TCbMe0Jj0R41QQV',object_kind:'payment_intent',provider_id:'pi1',account_id:'owner',evidence_ref:'fixture-proof',first_observed_at:'2026-10-05T00:00:00Z',provenance_version:1};const manifest={schema_version:1,checkpoint_id:'fixture-checkpoint',created_at:'2026-10-05T00:00:00Z',platforms:[{alias:'legacy',account_id:mapping.stripe_platform_account_id,mode:'live',history:{from:'2026-01-01',to:'2026-10-05',evidence_ref:'inventory'}},{alias:'auxilo_llc',account_id:'acct_1UMsxYLVAUzbAOHI',mode:'live',history:{from:'2026-01-01',to:'2026-10-05',evidence_ref:'inventory'}}],files,wal:{entries:[],listing_sha256:sha('[]')},objects:[mapping],hold_origins:[{account_id:'owner',payment_intent:'pi1',stripe_platform:'legacy',stripe_platform_account_id:mapping.stripe_platform_account_id,evidence_ref:'fixture-proof'}],initialization:{'stripe-object-origins.json':'absent','stripe-checkout-intents.json':'absent','stripe-event-receipts.json':'absent','stripe-connect-intents.json':'absent'},approval_ref:'fixture-only'};return{inputDir,outputDir,manifest,isolatedFixture:true,approved:true};}
test('dry run validates inventory and preserves all economic values and append logs',()=>{const f=fixture();const p=migration.planMigration(f);assert.equal(fs.existsSync(f.outputDir),false);assert.equal(p.economic_before,p.economic_after);const a=migration.applyMigration(f);assert.equal(a.state,'completed');for(const n of['purchases.jsonl','withdrawals.jsonl'])assert.deepEqual(fs.readFileSync(path.join(f.inputDir,n)),fs.readFileSync(path.join(f.outputDir,n)));const hold=JSON.parse(fs.readFileSync(path.join(f.outputDir,'account-holds.json'))).owner;assert.equal(hold.held_at,'old');assert.equal(hold.detail.remaining_usd,7);assert.equal(hold.detail.stripe_platform,'legacy');assert.equal(migration.applyMigration(f).state,'completed');});
for(const defect of['missing','corrupt','checksum','duplicate','revision','wal'])test('invalid '+defect+' inventory refuses any apply',()=>{const f=fixture();if(defect==='missing')fs.unlinkSync(path.join(f.inputDir,'earnings.json'));if(defect==='corrupt'){fs.writeFileSync(path.join(f.inputDir,'credits.json'),'{');f.manifest.files['credits.json'].sha256=sha('{');}if(defect==='checksum')f.manifest.files['credits.json'].sha256='0'.repeat(64);if(defect==='duplicate')f.manifest.objects.push({...f.manifest.objects[0],account_id:'other'});if(defect==='revision')f.manifest.schema_version=2;if(defect==='wal')fs.writeFileSync(path.join(f.inputDir,'wal','unlisted.json'),'{}');assert.throws(()=>migration.applyMigration(f));assert.equal(fs.existsSync(f.outputDir),false);});
test('unknown origin is preserved and aggregate report is masked and not cash',()=>{const f=fixture();f.manifest.objects=[];f.manifest.hold_origins=[];const report=reconcile.reconcileMigration(f);assert.ok(report.unknown_origin>0);assert.equal(report.provider_cash,'unverified');assert.equal(JSON.stringify(report).includes('owner'),false);assert.equal(JSON.stringify(report).includes('pi1'),false);migration.applyMigration(f);assert.deepEqual(JSON.parse(fs.readFileSync(path.join(f.outputDir,'account-holds.json'))),JSON.parse(fs.readFileSync(path.join(f.inputDir,'account-holds.json'))));});
test('partial journal blocks action and resumes forward at every output write',()=>{for(let crash=1;crash<=12;crash++){const f=fixture();assert.throws(()=>migration.applyMigration({...f,afterWrite:(_,i)=>{if(i===crash)throw Error('synthetic crash');}}),/synthetic crash/);const file=path.join(f.outputDir,'stripe-migration-journal.json');assert.throws(()=>migration.assertMigrationJournalComplete({file}),/incomplete/);assert.equal(migration.recoverMigration(f).state,'completed');assert.equal(migration.assertMigrationJournalComplete({file}).state,'completed');}});
test('journal corruption and unrelated output writer refuse recovery',()=>{const f=fixture();assert.throws(()=>migration.applyMigration({...f,afterWrite:()=>{throw Error('crash');}}));fs.writeFileSync(path.join(f.outputDir,'earnings.json'),'{}');assert.throws(()=>migration.recoverMigration(f),/drift/);fs.writeFileSync(path.join(f.outputDir,'stripe-migration-journal.json'),'{');assert.throws(()=>migration.assertMigrationJournalComplete({file:path.join(f.outputDir,'stripe-migration-journal.json')}));});
test('absent journal is explicitly unarmed',()=>assert.equal(migration.assertMigrationJournalComplete({file:path.join(os.tmpdir(),crypto.randomUUID())}).state,'unarmed'));
test('operational paths and missing isolated authority rejected',()=>{const f=fixture();assert.throws(()=>migration.applyMigration({...f,isolatedFixture:false}));assert.throws(()=>migration.applyMigration({...f,approved:false}));assert.throws(()=>migration.planMigration({...f,inputDir:'/data'}));});

test('all initialized stores have matching manifest bindings',()=>{const f=fixture();migration.applyMigration(f);for(const name of ['stripe-object-origins.json','stripe-checkout-intents.json','stripe-event-receipts.json','stripe-connect-intents.json']){const store=JSON.parse(fs.readFileSync(path.join(f.outputDir,name)));assert.equal((store.manifest||store.initialization_manifest).checkpoint_id,f.manifest.checkpoint_id);}});
test('unlisted existing new store cannot be treated as absent',()=>{const f=fixture();fs.writeFileSync(path.join(f.inputDir,'stripe-checkout-intents.json'),'{}');assert.throws(()=>migration.planMigration(f),/omitted/);});
test('missing new-store initialization attestation refuses plan',()=>{const f=fixture();delete f.manifest.initialization['stripe-checkout-intents.json'];assert.throws(()=>migration.planMigration(f),/attestation/);});
test('active maintenance writer blocks recovery',()=>{const f=fixture();assert.throws(()=>migration.applyMigration({...f,afterWrite:()=>{throw Error('crash');}}));fs.writeFileSync(path.join(f.outputDir,'.stripe-migration-maintenance.lock'),String(process.pid));assert.throws(()=>migration.recoverMigration(f),/writer already active/);});

test('masked report retains measured ledger amounts and zero unresolved attempt count',()=>{const f=fixture();const report=reconcile.reconcileMigration(f);assert.deepEqual(report.totals,{paid_principal:10,paid_remaining:7,promo_remaining:2,earnings_pending:3.15,refunded:0,removed:0,withdrawals:0,holds:1});assert.equal(report.unresolved_attempts,0);});
test('legacy cap-cache session key receives proven origin without field invention',()=>{const f=fixture();const record={cs_old:{account_id:'owner',amount_usd:10,created_at:1,expires_at:2}};const bytes=JSON.stringify(record);fs.writeFileSync(path.join(f.inputDir,'checkout-sessions.json'),bytes);f.manifest.files['checkout-sessions.json'].sha256=sha(bytes);f.manifest.objects.push({...f.manifest.objects[0],object_kind:'checkout_session',provider_id:'cs_old'});migration.applyMigration(f);const after=JSON.parse(fs.readFileSync(path.join(f.outputDir,'checkout-sessions.json'))).cs_old;assert.equal(after.stripe_platform,'legacy');assert.equal(after.session_id,undefined);assert.equal(after.expires_at,2);});
test('wrong-typed monetary scalar cannot become a null report total',()=>{const f=fixture();const bytes=JSON.stringify({owner:{pending_balance:'3.15'}});fs.writeFileSync(path.join(f.inputDir,'earnings.json'),bytes);f.manifest.files['earnings.json'].sha256=sha(bytes);assert.throws(()=>migration.planMigration(f),/amount schema/);});

test('verified legacy connected-account mapping backfills once without overwriting legacy identity',()=>{const f=fixture();const account={owner:{id:'owner',stripe_connect_id:'acct_fixture_builder'}};const bytes=JSON.stringify(account);fs.writeFileSync(path.join(f.inputDir,'accounts.json'),bytes);f.manifest.files['accounts.json'].sha256=sha(bytes);f.manifest.objects.push({...f.manifest.objects[0],object_kind:'connected_account',provider_id:'acct_fixture_builder'});const plan=migration.planMigration(f);assert.equal(plan.economic_before,plan.economic_after);migration.applyMigration(f);const file=path.join(f.outputDir,'accounts.json');const first=fs.readFileSync(file,'utf8');const after=JSON.parse(first).owner;assert.equal(after.stripe_connect_id,'acct_fixture_builder');assert.equal(after.stripe_connect_accounts.legacy.connected_id,'acct_fixture_builder');assert.equal(after.stripe_connect_accounts.legacy.evidence.approval_ref,'fixture-only');migration.applyMigration(f);assert.equal(fs.readFileSync(file,'utf8'),first);});
test('verified map cannot replace a different old legacy connected ID',()=>{const f=fixture();const bytes=JSON.stringify({owner:{id:'owner',stripe_connect_id:'acct_original'}});fs.writeFileSync(path.join(f.inputDir,'accounts.json'),bytes);f.manifest.files['accounts.json'].sha256=sha(bytes);f.manifest.objects.push({...f.manifest.objects[0],object_kind:'connected_account',provider_id:'acct_replacement'});assert.throws(()=>migration.planMigration(f),/mapping conflict/);});
test('rollback CLI checks actual completed schema and refuses snapshot/old binary',()=>{const f=fixture();migration.applyMigration(f);const {main}=require('../scripts/stripe-account-migration');const args=['--mode','rollback-check','--output',f.outputDir,'--isolated-fixture','--current-schema','1','--target-schema','1','--preserve-histories'];assert.equal(main(args).rollback_safe,true);assert.throws(()=>main([...args,'--restore-snapshot']),/snapshot/);assert.throws(()=>main([...args,'--target-schema','0']),/schema/);assert.throws(()=>main([...args,'--current-schema','0']),/schema/);});

for(const name of ['purchases.jsonl','withdrawals.jsonl'])test('unclassified append-only '+name+' prevents zero-unknown migration report',()=>{const f=fixture();const row=name==='purchases.jsonl'?{id:'pur_unknown',account_id:'owner',stripe_session_id:'cs_unclassified',stripe_payment_intent:'pi_unclassified',amount_usd:10}:{id:'wd_unknown',account_id:'owner',rail:'stripe',stripe_transfer_id:'tr_unclassified',amount_usd:10};const bytes=JSON.stringify(row)+'\n';fs.writeFileSync(path.join(f.inputDir,name),bytes);f.manifest.files[name].sha256=sha(bytes);const report=reconcile.reconcileMigration(f);assert.ok(report.unknown_origin>0);migration.applyMigration(f);assert.equal(fs.readFileSync(path.join(f.outputDir,name),'utf8'),bytes);});
test('missing owner and legacy unit-only purchases never become classified by bare provider ID',()=>{const f=fixture();f.manifest.objects.push({...f.manifest.objects[0],object_kind:'checkout_session',provider_id:'cs_units'});const bytes=JSON.stringify({id:'pur_units',stripe_session_id:'cs_units',stripe_payment_intent:'pi1',query_credits:400,unlock_credits:80})+'\n';fs.writeFileSync(path.join(f.inputDir,'purchases.jsonl'),bytes);f.manifest.files['purchases.jsonl'].sha256=sha(bytes);const report=reconcile.reconcileMigration(f);assert.ok(report.unknown_origin>0);assert.ok(report.unknown_units>0);});
test('fully mapped historical purchase contributes to classified count with no log rewrite',()=>{const f=fixture();f.manifest.objects.push({...f.manifest.objects[0],object_kind:'checkout_session',provider_id:'cs_known'});const bytes=JSON.stringify({id:'pur_known',account_id:'owner',stripe_session_id:'cs_known',stripe_payment_intent:'pi1',amount_usd:10})+'\n';fs.writeFileSync(path.join(f.inputDir,'purchases.jsonl'),bytes);f.manifest.files['purchases.jsonl'].sha256=sha(bytes);const report=reconcile.reconcileMigration(f);assert.equal(report.unknown_origin,0);assert.equal(report.classified,2);migration.applyMigration(f);assert.equal(fs.readFileSync(path.join(f.outputDir,'purchases.jsonl'),'utf8'),bytes);});
test('stored platform that contradicts attested purchase ownership is reported unresolved',()=>{const f=fixture();f.manifest.objects.push({...f.manifest.objects[0],object_kind:'checkout_session',provider_id:'cs_conflict'});const bytes=JSON.stringify({id:'pur_conflict',account_id:'owner',stripe_session_id:'cs_conflict',stripe_payment_intent:'pi1',amount_usd:10,stripe_platform:'auxilo_llc',stripe_platform_account_id:'acct_1UMsxYLVAUzbAOHI'})+'\n';fs.writeFileSync(path.join(f.inputDir,'purchases.jsonl'),bytes);f.manifest.files['purchases.jsonl'].sha256=sha(bytes);const report=reconcile.reconcileMigration(f);assert.ok(report.unknown_origin>0);assert.ok(report.origin_conflicts>0);});
