 'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const os=require('os');const path=require('path');const {digestJSON}=require('../lib/stripe-transfer-persistence');
const {initializeOrigins,createOriginStore}=require('../lib/stripe-object-origins');const{initializeEventReceipts,createEventReceiptStore}=require('../lib/stripe-event-receipts');const{createStripeEventDispatcher}=require('../lib/stripe-event-dispatch');
const legacy={stripe_platform:'legacy',stripe_platform_account_id:'acct_1TCbMe0Jj0R41QQV',livemode:true,mode:'live'};const newer={stripe_platform:'auxilo_llc',stripe_platform_account_id:'acct_1UMsxYLVAUzbAOHI',livemode:true,mode:'live'};
const ref={checkpoint_id:'fixture',manifest_sha256:'c'.repeat(64),approval_ref:'fixture-only',inventory_complete:true};
function event(id='evt_same',session='cs_same'){return{id,type:'checkout.session.completed',livemode:true,created:1791244800,data:{object:{id:session,object:'checkout.session',mode:'payment',payment_status:'paid',livemode:true,currency:'usd',amount_total:1000,payment_intent:'pi_same',metadata:{account_id:'owner',pack_id:'starter'}}}};}
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'auxilo-webhook-'));const of=path.join(dir,'origins.json'),ef=path.join(dir,'events.json');initializeOrigins(of,ref);initializeEventReceipts(ef,ref);const origins=createOriginStore({file:of}),receipts=createEventReceiptStore({file:ef});const lots=new Map(),purchases=[];let failCredit=false,failAppend=false,failComplete=false;const counts={lot:0,append:0,effects:0,refund:0,save:0,provider:0};const o=(c,session='cs_same')=>origins.record({...c,object_kind:'checkout_session',provider_id:session,account_id:'owner',evidence_ref:'approved-history',first_observed_at:'2026-10-05T00:00:00Z',provenance_version:1});
const realComplete=receipts.complete;receipts.complete=(...a)=>{if(failComplete){failComplete=false;throw Error('synthetic receipt failure');}return realComplete(...a);};
const deps={origins,receipts,packs:{starter:{price_usd:10,price_cents:1000}},getAccounts:()=>({owner:{id:'owner'}}),getEarnings:()=>({builder:{pending_balance:5}}),saveEarnings:async()=>{counts.save++;},getPurchases:(owner,c)=>purchases.filter(p=>p.account_id===owner&&p.stripe_platform===c.stripe_platform),isSessionProcessed:(id,c)=>purchases.some(p=>p.stripe_session_id===id&&p.stripe_platform===c.stripe_platform),addDollarLot:async(owner,kind,amount,opts)=>{if(failCredit){failCredit=false;return{success:false};}assert.ok(origins.find(opts,'purchase_identity','cs_same')||origins.all().some(o=>o.purchase_id===opts.purchase_id));const k=opts.stripe_platform+':'+opts.stripe_payment_intent;if(!lots.has(k)){lots.set(k,{owner,amount,opts});counts.lot++;}return{success:true,lot_id:k};},appendPurchase:p=>{if(failAppend){failAppend=false;throw Error('synthetic append failure');}if(!purchases.some(x=>x.stripe_platform===p.stripe_platform&&x.stripe_session_id===p.stripe_session_id)){purchases.push(p);counts.append++;}},clearPending:()=>{},postCreditEffects:async()=>{counts.effects++;},refundHandlers:{handleDisputeCreated:async(e,c)=>{assert.ok(c.stripeContext);counts.refund++;return{matched:true};},handleDisputeClosed:async(e,c)=>{assert.ok(c.stripeContext);await c.saveEarnings();counts.refund++;return{matched:true};},handleChargeRefunded:async(e,c)=>{assert.ok(c.stripeContext);counts.refund++;return{matched:true};}}};return{dir,of,ef,origins,receipts,lots,purchases,counts,deps,o,dispatch:(e,c=legacy)=>createStripeEventDispatcher(deps).dispatch(e,c,digestJSON(e)),fail:(what)=>{if(what==='credit')failCredit=true;if(what==='append')failAppend=true;if(what==='complete')failComplete=true;}};}
test('concurrent legacy endpoint aliases credit exactly once',async()=>{const f=fixture();f.o(legacy);const e=event();const results=await Promise.all([f.dispatch(e),f.dispatch(e)]);assert.ok(results.every(r=>r.status===200));assert.equal(f.counts.lot,1);assert.equal(f.counts.append,1);});
test('equal event/session/PI identifiers across platforms remain independent',async()=>{const f=fixture();f.o(legacy);f.o(newer);const e=event();await f.dispatch(e,legacy);await f.dispatch(e,newer);assert.equal(f.counts.lot,2);assert.equal(f.counts.append,2);assert.notEqual(f.purchases[0].id,f.purchases[1].id);});
for(const boundary of['credit','append','complete'])test('retry after '+boundary+' failure preserves purchase identity and credits once',async()=>{const f=fixture();f.o(legacy);f.fail(boundary);const e=event();assert.equal((await f.dispatch(e)).status,503);assert.notEqual(f.receipts.get('legacy',e.id).state,'completed');const identity=f.origins.find(legacy,'purchase_identity','cs_same');assert.ok(identity.purchase_id);assert.equal((await f.dispatch(e)).status,200);assert.equal(f.counts.lot,1);assert.equal(f.counts.append,1);assert.equal(f.purchases[0].id,identity.purchase_id);});
test('different event IDs for same session serialize the semantic identity',async()=>{const f=fixture();f.o(legacy);await Promise.all([f.dispatch(event('evt_a')),f.dispatch(event('evt_b'))]);assert.equal(f.counts.lot,1);assert.equal(f.counts.append,1);});
test('unknown historical money event is quarantined and does not credit',async()=>{const f=fixture();const e=event();assert.equal((await f.dispatch(e)).status,409);assert.equal(f.receipts.get('legacy',e.id).state,'quarantined');assert.equal(f.counts.lot,0);});
for(const [label,change]of[['wrong amount',e=>e.data.object.amount_total=999],['wrong currency',e=>e.data.object.currency='eur'],['wrong mode',e=>e.livemode=false],['unpaid',e=>e.data.object.payment_status='unpaid'],['missing owner',e=>e.data.object.metadata.account_id='unknown'],['unknown pack',e=>e.data.object.metadata.pack_id='other'],['connected context',e=>e.account='acct_external'],['wrong owner provenance',e=>{}]])test(label+' cannot mutate financial state',async()=>{const f=fixture();f.o(label==='wrong owner provenance'?newer:legacy);const e=event();change(e);assert.notEqual((await f.dispatch(e)).status,200);assert.equal(f.counts.lot,0);assert.equal(f.counts.append,0);assert.equal(f.counts.provider,0);});
test('durable exact Checkout intent can attest late completion after active platform changes',async()=>{const f=fixture();const e=event();e.data.object.metadata.auxilo_checkout_intent_id='intent1';let paid=0;f.deps.checkoutIntents={all:()=>[{intent_id:'intent1',account_id:'owner',pack_id:'starter',amount_cents:1000,currency:'usd',...legacy,state:'unknown'}],transition:()=>{},recordPaid:()=>{paid++;}};assert.equal((await f.dispatch(e)).status,200);assert.equal(f.origins.find(legacy,'checkout_session','cs_same').account_id,'owner');assert.equal(f.purchases[0].stripe_platform,'legacy');assert.equal(paid,1);});
test('intent metadata cannot redirect another owner or platform',async()=>{const f=fixture();const e=event();e.data.object.metadata.auxilo_checkout_intent_id='intent1';f.deps.checkoutIntents={all:()=>[{intent_id:'intent1',account_id:'other',pack_id:'starter',amount_cents:1000,currency:'usd',...newer,state:'unknown'}]};assert.equal((await f.dispatch(e)).status,409);assert.equal(f.counts.lot,0);});
test('same event ID divergent payload never retries financial effects',async()=>{const f=fixture();f.o(legacy);const e=event();assert.equal((await f.dispatch(e)).status,200);e.data.object.amount_total=2000;assert.notEqual((await f.dispatch(e)).status,200);assert.equal(f.counts.lot,1);});
test('post-credit cap/referral bookkeeping failures stay nonfatal',async()=>{const f=fixture();f.o(legacy);f.deps.clearPending=()=>{throw Error('cache');};f.deps.postCreditEffects=()=>{throw Error('alert');};assert.equal((await f.dispatch(event())).status,200);assert.equal(f.counts.lot,1);});
test('unmatched refund and conflicting hold are durable quarantine outcomes',async()=>{for(const reason of['unknown','conflict']){const f=fixture();f.deps.refundHandlers.handleDisputeCreated=async()=>reason==='unknown'?{matched:false}:{matched:true,hold_conflict:true};const e={id:'evt_dispute',type:'charge.dispute.created',livemode:true,data:{object:{id:'dp1',payment_intent:'pi1'}}};assert.equal((await f.dispatch(e)).status,409);assert.equal(f.receipts.get('legacy',e.id).state,'quarantined');}});
test('earnings save failure cannot mark reversal receipt complete',async()=>{const f=fixture();f.deps.saveEarnings=async()=>{throw Error('synthetic mandatory earnings write');};const e={id:'evt_close',type:'charge.dispute.closed',livemode:true,data:{object:{id:'dp1',payment_intent:'pi1'}}};assert.equal((await f.dispatch(e)).status,503);assert.notEqual(f.receipts.get('legacy',e.id).state,'completed');});
test('unknown nonfinancial event is safely ignored',async()=>{const f=fixture();const e={id:'evt_ignore',type:'customer.updated',livemode:true,data:{object:{id:'cus1'}}};assert.equal((await f.dispatch(e)).status,200);assert.equal(f.counts.lot,0);});
test('platform signing routes reject the opposite platform secret and connected events',()=>{const {createPlatformRegistry}=require('../lib/stripe-platforms');const env={STRIPE_SECRET_KEY:'sk_live_'+'a'.repeat(30),STRIPE_WEBHOOK_SECRET:'whsec_'+'a'.repeat(30),STRIPE_AUXILO_LLC_SECRET_KEY:'sk_live_'+'b'.repeat(30),STRIPE_AUXILO_LLC_WEBHOOK_SECRET:'whsec_'+'b'.repeat(30)};const reg=createPlatformRegistry({env,verifier:(raw,sig,secret)=>{assert.equal(sig,secret);return JSON.parse(raw);},clientFactory:()=>{throw Error('API provider calls forbidden');}});const raw=JSON.stringify(event());assert.equal(reg.verifyPlatformEvent('legacy',raw,env.STRIPE_WEBHOOK_SECRET).context.stripe_platform,'legacy');assert.equal(reg.verifyPlatformEvent('auxilo_llc',raw,env.STRIPE_AUXILO_LLC_WEBHOOK_SECRET).context.stripe_platform,'auxilo_llc');assert.throws(()=>reg.verifyPlatformEvent('auxilo_llc',raw,env.STRIPE_WEBHOOK_SECRET));assert.throws(()=>reg.verifyPlatformEvent('legacy',JSON.stringify({...event(),account:'acct_external'}),env.STRIPE_WEBHOOK_SECRET));});

test('real unknown intent resolves by signed event and durable credit before admission release',async()=>{const f=fixture();const{initializeCheckoutIntents,createCheckoutIntentStore}=require('../lib/stripe-checkout-intents');const file=path.join(f.dir,'intents.json');initializeCheckoutIntents(file,ref);const store=createCheckoutIntentStore({file});let intent=store.prepare({...legacy,configuration_generation:'fixture',account_id:'owner',pack_id:'starter',amount_cents:1000,currency:'usd',base_url:'https://example.test'});intent=store.transition(intent.intent_id,intent.generation,'submitted');intent=store.transition(intent.intent_id,intent.generation,'unknown');f.deps.checkoutIntents=store;const e=event();e.data.object.metadata.auxilo_checkout_intent_id=intent.intent_id;f.fail('append');assert.equal((await f.dispatch(e)).status,503);assert.equal(store.blocking('owner').state,'paid_pending_credit');assert.equal((await f.dispatch(e)).status,200);assert.equal(store.blocking('owner'),null);assert.equal(store.get(intent.intent_id).state,'paid_credited');assert.equal(f.counts.lot,1);});
test('durable completed receipt replay after fresh store reload performs no financial effect',async()=>{const f=fixture();f.o(legacy);const e=event();assert.equal((await f.dispatch(e)).status,200);f.deps.receipts=createEventReceiptStore({file:f.ef});f.deps.origins=createOriginStore({file:f.of});assert.equal((await f.dispatch(e)).status,200);assert.equal(f.counts.lot,1);assert.equal(f.counts.append,1);});

test('divergent receipt digest alerts existing sink without raw event content',async()=>{const f=fixture();f.o(legacy);const alerts=[];f.deps.sendOpsAlert=(...args)=>alerts.push(args);const e=event();await f.dispatch(e);e.data.object.amount_total=4000;assert.equal((await f.dispatch(e)).status,503);assert.equal(alerts.length,1);assert.ok(!JSON.stringify(alerts).includes('metadata'));assert.equal(f.counts.lot,1);});
test('mandatory fsync failure calls fatal financial storage callback before retry response',async()=>{const f=fixture();f.o(legacy);let fatal=0;f.deps.onFatalStorage=e=>{assert.equal(e.financialStorageFailure,true);fatal++;};f.deps.appendPurchase=()=>{const e=Error('synthetic fsync');e.financialStorageFailure=true;throw e;};assert.equal((await f.dispatch(event())).status,503);assert.equal(fatal,1);assert.notEqual(f.receipts.get('legacy','evt_same').state,'completed');});
