'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const {initializeCheckoutIntents,createCheckoutIntentStore,checkoutFingerprint}=require('../lib/stripe-checkout-intents');
const {initializeEventReceipts,createEventReceiptStore}=require('../lib/stripe-event-receipts');
const ref={checkpoint_id:'cp-test',manifest_sha256:'a'.repeat(64),inventory_complete:true,approval_ref:'approval-test'};
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'checkout-state-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return path.join(dir,'state.json');}
function input(){return{account_id:'owner',stripe_platform:'legacy',stripe_platform_account_id:'acct_1TCbMe0Jj0R41QQV',configuration_generation:1,livemode:false,pack_id:'pack',currency:'usd',amount_cents:1000,base_url:'https://example.test'};}
function store(t){const file=temp(t);initializeCheckoutIntents(file,ref);return{file,s:createCheckoutIntentStore({file})};}
test('missing checkout intent store blocks rather than initializes',t=>{const file=temp(t),s=createCheckoutIntentStore({file});assert.equal(s.ready,false);assert.throws(()=>s.prepare(input()));assert.equal(fs.existsSync(file),false);});
test('initialization requires complete bound evidence',t=>{assert.throws(()=>initializeCheckoutIntents(temp(t),{...ref,inventory_complete:false}));});
test('prepared attempt has fixed request and platform before provider call',t=>{const{s}=store(t),a=s.prepare(input());assert.equal(a.state,'prepared');assert.ok(a.intent_id);assert.ok(a.idempotency_key);assert.equal(a.fingerprint,checkoutFingerprint(input()));assert.equal(s.blocking('owner').intent_id,a.intent_id);});
test('restart/cache expiry/different platform and pack cannot create substitute intent',t=>{const{file,s}=store(t),a=s.prepare(input());s.transition(a.intent_id,a.generation,'submitted');const restart=createCheckoutIntentStore({file});assert.throws(()=>restart.prepare({...input(),pack_id:'different',stripe_platform:'auxilo_llc',stripe_platform_account_id:'acct_1UMsxYLVAUzbAOHI'}));assert.equal(restart.all().length,1);});
test('submitted cannot resend and immutable context cannot change',t=>{const{s}=store(t),a=s.prepare(input()),b=s.transition(a.intent_id,a.generation,'submitted');assert.throws(()=>s.transition(b.intent_id,b.generation,'submitted'));assert.throws(()=>s.transition(b.intent_id,b.generation,'unknown',{stripe_platform:'auxilo_llc'}));});
test('unknown never terminal on elapsed time or missing search hit',t=>{const{s}=store(t),a=s.prepare(input()),b=s.transition(a.intent_id,a.generation,'submitted'),u=s.transition(b.intent_id,b.generation,'unknown');assert.throws(()=>s.transition(u.intent_id,u.generation,'confirmed_not_created',{evidence:{search_empty:true}}));assert.ok(s.blocking('owner'));});
test('confirmed open reuses recorded session; expiration alone remains unresolved',t=>{const{s}=store(t),a=s.prepare(input()),b=s.transition(a.intent_id,a.generation,'submitted');const row=s.transition(b.intent_id,b.generation,'confirmed_open',{session_id:'cs_test_a',session_url:'https://checkout.stripe.com/test',expires_at:Date.now()+60000,evidence:{verified:true,authoritative:true,stripe_platform:b.stripe_platform,stripe_platform_account_id:b.stripe_platform_account_id,livemode:false,evidence_ref:'provider-read',intent_id:b.intent_id,account_id:b.account_id,amount_cents:b.amount_cents,currency:b.currency,session_id:'cs_test_a'},cap_state_durable:true});assert.equal(s.findOpen('owner',a.fingerprint,Date.now()).session_id,row.session_id);assert.ok(s.blocking('owner',Date.now()+120000));});
test('paid receipt requires durable credit and cannot cross platform',t=>{const{s}=store(t),a=s.prepare(input());s.transition(a.intent_id,a.generation,'submitted');assert.throws(()=>s.recordPaid({...input(),stripe_platform:'auxilo_llc'},'cs_test_a','purchase'));});
test('corrupt checksum prevents admission after restart',t=>{const{file,s}=store(t);s.prepare(input());const x=JSON.parse(fs.readFileSync(file));Object.values(x.intents)[0].amount_cents=1;fs.writeFileSync(file,JSON.stringify(x));assert.equal(createCheckoutIntentStore({file}).ready,false);});
function receipt(){return{stripe_platform:'legacy',stripe_platform_account_id:'acct_1TCbMe0Jj0R41QQV',event_id:'evt_a',event_type:'checkout.session.completed',object_id:'cs_test_a',payload_digest:'b'.repeat(64),purchase_id:'p_a'};}
test('event replay shares platform namespace and rejects divergent digest',t=>{const file=temp(t);initializeEventReceipts(file,ref);const s=createEventReceiptStore({file}),a=s.begin(receipt());assert.equal(s.begin(receipt()).receipt_id,a.receipt_id);assert.throws(()=>s.begin({...receipt(),payload_digest:'c'.repeat(64)}));assert.equal(s.begin({...receipt(),stripe_platform:'auxilo_llc',stripe_platform_account_id:'acct_1UMsxYLVAUzbAOHI'}).state,'processing');});
test('uncompleted and quarantined receipts remain retriable after restart',t=>{const file=temp(t);initializeEventReceipts(file,ref);const s=createEventReceiptStore({file});s.begin(receipt());s.quarantine('legacy','evt_a','unknown_origin');const r=createEventReceiptStore({file});assert.equal(r.begin(receipt()).state,'quarantined');});
test('same-object distinct events serialize before effects',async t=>{const file=temp(t);initializeEventReceipts(file,ref);const s=createEventReceiptStore({file});let active=0,max=0;await Promise.all(['evt_a','evt_b'].map(id=>s.withLocks(receipt(),{id,data:{object:{id:'cs_test_a'}}},async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,10));active--;})));assert.equal(max,1);});

function evidence(row,patch={}){return{verified:true,authoritative:true,evidence_ref:'provider-read',intent_id:row.intent_id,account_id:row.account_id,amount_cents:row.amount_cents,currency:row.currency,stripe_platform:row.stripe_platform,stripe_platform_account_id:row.stripe_platform_account_id,livemode:row.livemode,...patch};}
test('paid credit is terminal only after durable financial effects',t=>{const{s}=store(t),a=s.prepare(input()),b=s.transition(a.intent_id,a.generation,'submitted');const paid=s.transition(b.intent_id,b.generation,'paid_pending_credit',{session_id:'cs_test_a',evidence:evidence(b,{session_id:'cs_test_a'})});assert.ok(s.blocking('owner'));assert.throws(()=>s.transition(paid.intent_id,paid.generation,'paid_credited',{purchase_id:'purchase'}));const done=s.recordPaid(input(),'cs_test_a','purchase');assert.equal(done.state,'paid_credited');assert.equal(s.blocking('owner'),null);assert.equal(s.recordPaid(input(),'cs_test_a','purchase').generation,done.generation);assert.throws(()=>s.recordPaid(input(),'cs_test_a','different'));});
test('terminal evidence bound to another intent cannot release admission',t=>{const{s}=store(t),a=s.prepare(input());assert.throws(()=>s.transition(a.intent_id,a.generation,'confirmed_not_created',{evidence:evidence(a,{intent_id:'other',definitive_not_created:true})}));assert.ok(s.blocking('owner'));});
test('authoritative no creation releases hold without pruning evidence',t=>{const{s}=store(t),a=s.prepare(input());s.transition(a.intent_id,a.generation,'confirmed_not_created',{cap_state_durable:true,evidence:evidence(a,{definitive_not_created:true})});assert.equal(s.blocking('owner'),null);assert.equal(s.all().length,1);assert.ok(s.prepare(input()).intent_id);});
test('authoritative expired unpaid requires durable cap resolution',t=>{const{s}=store(t),a=s.prepare(input()),b=s.transition(a.intent_id,a.generation,'submitted'),patch={session_id:'cs_test_a',evidence:evidence(b,{session_id:'cs_test_a',expired_unpaid:true})};assert.throws(()=>s.transition(b.intent_id,b.generation,'confirmed_expired_unpaid',patch));s.transition(b.intent_id,b.generation,'confirmed_expired_unpaid',{...patch,cap_state_durable:true});assert.equal(s.blocking('owner'),null);});
test('different signed events cannot change persisted semantic purchase identity',t=>{const file=temp(t);initializeEventReceipts(file,ref);const s=createEventReceiptStore({file});s.begin(receipt());assert.throws(()=>s.begin({...receipt(),event_id:'evt_b',purchase_id:'different'}));});
test('receipt completion survives restart and forbids later quarantine',t=>{const file=temp(t);initializeEventReceipts(file,ref);const s=createEventReceiptStore({file});s.begin(receipt());s.complete('legacy','evt_a',{disposition:'credited'});const restart=createEventReceiptStore({file});assert.equal(restart.begin(receipt()).state,'completed');assert.throws(()=>restart.quarantine('legacy','evt_a','unknown'));});
test('receipt store refuses raw event payloads and corrupt state',t=>{const file=temp(t);initializeEventReceipts(file,ref);const s=createEventReceiptStore({file});assert.throws(()=>s.begin({...receipt(),raw_body:'customer data'}));fs.writeFileSync(file,'{}');assert.equal(createEventReceiptStore({file}).ready,false);});

function cache(t){const file=temp(t);const old=process.env.AUXILO_CHECKOUT_SESSIONS_FILE;process.env.AUXILO_CHECKOUT_SESSIONS_FILE=file;delete require.cache[require.resolve('../lib/checkout-sessions')];const m=require('../lib/checkout-sessions');t.after(()=>{delete require.cache[require.resolve('../lib/checkout-sessions')];if(old===undefined)delete process.env.AUXILO_CHECKOUT_SESSIONS_FILE;else process.env.AUXILO_CHECKOUT_SESSIONS_FILE=old;});return{file,m};}
test('cap cache sums both platforms and clears only matching origin',t=>{const{m}=cache(t),legacy=input(),llc={...input(),stripe_platform:'auxilo_llc',stripe_platform_account_id:'acct_1UMsxYLVAUzbAOHI'},now=Date.now();const a=m.reservePendingSession('owner',10,now,legacy),b=m.reservePendingSession('owner',20,now,llc);m.promoteReservation(a,'cs_equal','owner',10,Math.floor(now/1000)+1000,now,legacy);m.promoteReservation(b,'cs_equal','owner',20,Math.floor(now/1000)+1000,now,llc);assert.equal(m.getPendingSessionsTotalUsd('owner',now),30);m.clearPendingSession('cs_equal',llc);assert.equal(m.getPendingSessionsTotalUsd('owner',now),10);});
test('atomic cache promotion leaves reservation intact when replacement fails',t=>{const{m,file}=cache(t),now=Date.now(),context=input(),id=m.reservePendingSession('owner',10,now,context),before=fs.readFileSync(file,'utf8');assert.throws(()=>m.promoteReservation(id,'cs_test','other',10,Math.floor(now/1000)+1000,now,context));assert.equal(fs.readFileSync(file,'utf8'),before);});
test('cap cache pruning never deletes durable unknown intent',t=>{const{s}=store(t),a=s.prepare(input()),{m}=cache(t);const past=Date.now()-600000;m.reservePendingSession('owner',10,past,input());assert.equal(m.getPendingSessionsTotalUsd('owner'),0);m.save({});assert.equal(s.blocking('owner').intent_id,a.intent_id);});
test('unproven historical cache row never clears through platform event',t=>{const{m}=cache(t),now=Date.now();m.save({cs_test:{account_id:'owner',amount_usd:10,created_at:now,expires_at:now+60000}});m.clearPendingSession('cs_test',input());assert.equal(m.getPendingSessionsTotalUsd('owner'),10);});

test('quarantined unknown origin can bind verified purchase once and complete',t=>{const file=temp(t);initializeEventReceipts(file,ref);const s=createEventReceiptStore({file}),unknown={...receipt()};delete unknown.purchase_id;s.begin(unknown);s.quarantine('legacy','evt_a','unknown_origin');assert.equal(s.begin(receipt()).purchase_id,'p_a');s.complete('legacy','evt_a');assert.throws(()=>s.begin({...receipt(),purchase_id:'p_changed'}));});

test('definitive no-create evidence alone cannot release unresolved cap state',t=>{const{s}=store(t),a=s.prepare(input());assert.throws(()=>s.transition(a.intent_id,a.generation,'confirmed_not_created',{evidence:evidence(a,{definitive_not_created:true})}));assert.ok(s.blocking('owner'));});
test('distinct charge and dispute objects for one PI serialize financial effects',async t=>{const file=temp(t);initializeEventReceipts(file,ref);const s=createEventReceiptStore({file});let active=0,max=0;await Promise.all(['ch_a','du_b'].map((id,index)=>s.withLocks(receipt(),{id:'evt_'+index,data:{object:{id,payment_intent:'pi_shared'}}},async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,10));active--;})));assert.equal(max,1);});
