 'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const {createPlatformRegistry,PLATFORM_DEFINITIONS}=require('../lib/stripe-platforms');
const defs={legacy:{account_id:'acct_synthetic_old',secret_env:'OLD_KEY',webhook_env:'OLD_HOOK'},auxilo_llc:{account_id:'acct_synthetic_new',secret_env:'NEW_KEY',webhook_env:'NEW_HOOK'}};
function fixture(patch={}){const env={OLD_KEY:'sk_test_'+'x'.repeat(32),OLD_HOOK:'whsec_'+'a'.repeat(32),NEW_KEY:'sk_test_'+'y'.repeat(32),NEW_HOOK:'whsec_'+'b'.repeat(32)};let creates=0;const clients={};const r=createPlatformRegistry({definitions:defs,env,clientFactory:(key,alias)=>{creates++;return clients[alias]={accounts:{retrieve:async()=>({id:defs[alias].account_id})},balance:{retrieve:async()=>({livemode:false})},webhooks:{constructEvent:(raw,sig,secret)=>{if(sig!==secret)throw Error('signature');return JSON.parse(raw);}},...patch};}});return {r,env,clients,count:()=>creates};}
test('M01 authenticated account plus mode required despite successful balance',async()=>{for(const patch of [{accounts:{retrieve:async()=>({id:'acct_wrong'})}},{accounts:{retrieve:async()=>{throw Error('unavailable');}}},{balance:{retrieve:async()=>({livemode:true})}}]){const {r}=fixture(patch);assert.equal((await r.probePlatform('legacy')).configured,false);await assert.rejects(r.getVerifiedClient('legacy'));}});
test('M01 correct identity returns frozen opaque capability; forgery rejected',async()=>{const {r}=fixture();const {context,client}=await r.getVerifiedClient('legacy');assert.equal(context.stripe_platform_account_id,defs.legacy.account_id);assert.equal(Object.isFrozen(context),true);assert.equal(r.assertVerifiedContext(context),client);assert.throws(()=>r.assertVerifiedContext({...context}));});
test('M01 unknown aliases and duplicate registry identities rejected',()=>{const {r}=fixture();assert.throws(()=>r.getPlatform('arbitrary'));assert.throws(()=>createPlatformRegistry({definitions:{...defs,auxilo_llc:{...defs.legacy}},env:{},clientFactory:()=>({})}));});
test('M02 immutable production account cannot be overridden by env',async()=>{const env={STRIPE_SECRET_KEY:'sk_test_'+'x'.repeat(32),STRIPE_PLATFORM_ACCOUNT_ID:'acct_override'};let calls=0;const r=createPlatformRegistry({env,clientFactory:()=>{calls++;return {};}});assert.equal(r.getPlatform('legacy').account_id,PLATFORM_DEFINITIONS.legacy.account_id);assert.equal((await r.probePlatform('legacy')).configured,false);assert.equal(calls,0);});
test('M02 aliases cache independently; key generation drift revokes old context',async()=>{const {r,env,count}=fixture();const a=await r.getVerifiedClient('legacy');const b=await r.getVerifiedClient('legacy');assert.equal(a.client,b.client);await r.getVerifiedClient('auxilo_llc');assert.equal(count(),2);env.OLD_KEY+='z';assert.throws(()=>r.assertVerifiedContext(a.context));const c=await r.getVerifiedClient('legacy');assert.notEqual(c.context.configuration_generation,a.context.configuration_generation);});
test('M02 failing one platform never uses another client',async()=>{const {r,env,count}=fixture();delete env.OLD_KEY;await assert.rejects(r.getVerifiedClient('legacy'));assert.equal(count(),0);assert.equal((await r.getVerifiedClient('auxilo_llc')).context.stripe_platform,'auxilo_llc');});
test('M02 status preserves fields and does not expose secrets',async()=>{const {r,env}=fixture();await r.probePlatform('legacy');const s=r.getPlatformStatus('legacy');for(const k of ['configured','reason','checked_at','mode'])assert.ok(k in s);for(const v of Object.values(env))assert.ok(!JSON.stringify(s).includes(v));});
test('M03 signature verification works with failed API, refuses cross signature and wrong event context',()=>{const {r,env}=fixture();const event={id:'evt_synthetic',livemode:false};assert.equal(r.verifyPlatformEvent('legacy',JSON.stringify(event),env.OLD_HOOK).event.id,event.id);assert.throws(()=>r.verifyPlatformEvent('legacy',JSON.stringify(event),env.NEW_HOOK));assert.throws(()=>r.verifyPlatformEvent('legacy',JSON.stringify({...event,livemode:true}),env.OLD_HOOK));assert.throws(()=>r.verifyPlatformEvent('legacy',JSON.stringify({...event,account:'acct_connected'}),env.OLD_HOOK));});
test('M02 configuration assertion drift revokes existing API context before provider writes',async()=>{const definitions={...defs,legacy:{...defs.legacy,assertion_env:'EXPECTED'}};const env={OLD_KEY:'sk_test_'+'x'.repeat(32),EXPECTED:defs.legacy.account_id};const r=createPlatformRegistry({definitions,env,clientFactory:()=>({accounts:{retrieve:async()=>({id:defs.legacy.account_id})},balance:{retrieve:async()=>({livemode:false})}})});const {context}=await r.getVerifiedClient('legacy');env.EXPECTED='acct_wrong';assert.throws(()=>r.assertVerifiedContext(context));assert.equal((await r.probePlatform('legacy')).configured,false);});
test('M03 API authentication failure does not disable legitimate signed event verification',async()=>{const {r,env}=fixture({accounts:{retrieve:async()=>{const e=Error('rejected');e.statusCode=401;throw e;}}});assert.equal((await r.probePlatform('legacy')).configured,false);assert.equal(r.verifyPlatformEvent('legacy',JSON.stringify({id:'evt_synthetic',livemode:false}),env.OLD_HOOK).context.stripe_platform,'legacy');});
test('M01 drift during authenticated identity probe produces no capability',async()=>{const {r,env}=fixture({accounts:{retrieve:async()=>{env.OLD_KEY+='changed';return {id:defs.legacy.account_id};}}});await assert.rejects(r.getVerifiedClient('legacy'));});
