 'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'builder-map-'));process.env.AUXILO_ACCOUNTS_FILE=path.join(dir,'accounts.json');process.env.SESSION_SECRET='s'.repeat(40);fs.writeFileSync(process.env.AUXILO_ACCOUNTS_FILE,JSON.stringify({owner:{stripe_connect_id:'acct_historical'}}));
const accounts=require('../lib/accounts');const intents=require('../lib/stripe-connect-intents');
const context={stripe_platform:'legacy',stripe_platform_account_id:'acct_synthetic_platform',configuration_generation:'generation',mode:'test',livemode:false};const evidence={approval_ref:'synthetic-approval',evidence_ref:'synthetic-proof',disposition:'approved'};
test('M10 mapping requires explicit approval; immutable per platform and legacy ID preserved',async()=>{const {context}=await fakeProvider();assert.throws(()=>accounts.setStripeConnectMapping('owner',context,'acct_connected',{}));accounts.setStripeConnectMapping('owner',context,'acct_connected',evidence);assert.equal(accounts.getStripeConnectMapping('owner',context).connected_id,'acct_connected');assert.throws(()=>accounts.setStripeConnectMapping('owner',context,'acct_replacement',evidence));process.env.STRIPE_AUXILO_LLC_SECRET_KEY='sk_test_'+'n'.repeat(40);const r=registry.createPlatformRegistry({definitions:{...definitions,auxilo_llc:{...definitions.auxilo_llc,account_id:'acct_synthetic_new'}},clientFactory:()=>({accounts:{retrieve:async()=>({id:'acct_synthetic_new'})},balance:{retrieve:async()=>({livemode:false})}})});registry.__setRegistryForTest(r);const newContext=(await r.getVerifiedClient('auxilo_llc')).context;accounts.setStripeConnectMapping('owner',newContext,'acct_new',evidence);assert.equal(accounts.loadAccounts().owner.stripe_connect_id,'acct_historical');assert.throws(()=>accounts.getStripeConnectMapping('owner',{...context,stripe_platform_account_id:'acct_wrong'}));});
test('M10 strict map read refuses corrupt accounts without replacement',()=>{const bytes=fs.readFileSync(process.env.AUXILO_ACCOUNTS_FILE);fs.writeFileSync(process.env.AUXILO_ACCOUNTS_FILE,'{');assert.throws(()=>accounts.getStripeConnectMapping('owner',context));fs.writeFileSync(process.env.AUXILO_ACCOUNTS_FILE,bytes);});
test('M10 Connect unknown intent survives restart, cannot resend or mutate ownership',()=>{const file=path.join(dir,'connect.json');assert.throws(()=>intents.createConnectIntentStore({file}).all());intents.initializeConnectIntents(file,{checkpoint_id:'synthetic',manifest_sha256:'a'.repeat(64),inventory_complete:true,approval_ref:'approval'});let s=intents.createConnectIntentStore({file});const a=s.prepare({account_id:'owner',context,idempotency_key:'connect-key',approval_ref:'approval',evidence_ref:'proof'});s.transition(a.intent_id,'submitted');s.transition(a.intent_id,'unknown');s=intents.createConnectIntentStore({file});assert.equal(s.findForAccount('owner','legacy').state,'unknown');assert.throws(()=>s.prepare({account_id:'owner',context,idempotency_key:'different',approval_ref:'approval',evidence_ref:'proof'}));assert.throws(()=>s.transition(a.intent_id,'submitted'));assert.throws(()=>s.transition(a.intent_id,'account_created',{account_id:'other',connected_id:'acct_connected'}));});
test('M10 durable created account permits same-account completion only',()=>{const file=path.join(dir,'connect-created.json');intents.initializeConnectIntents(file,{checkpoint_id:'synthetic',manifest_sha256:'a'.repeat(64),inventory_complete:true,approval_ref:'approval'});const s=intents.createConnectIntentStore({file});const a=s.prepare({account_id:'owner2',context,idempotency_key:'key2',approval_ref:'approval',evidence_ref:'proof'});s.transition(a.intent_id,'submitted');s.transition(a.intent_id,'account_created',{connected_id:'acct_connected'});assert.throws(()=>s.transition(a.intent_id,'account_created',{connected_id:'acct_other'}));s.transition(a.intent_id,'completed');assert.equal(s.get(a.intent_id).connected_id,'acct_connected');});

const stripe = require('../lib/stripe');const registry = require('../lib/stripe-platforms');
const definitions = {...registry.PLATFORM_DEFINITIONS,legacy:{...registry.PLATFORM_DEFINITIONS.legacy,account_id:'acct_synthetic_platform'}};
async function fakeProvider(overrides={}) { process.env.STRIPE_SECRET_KEY='sk_test_'+'s'.repeat(40);let writes=0;const client={accounts:{retrieve:async id=>({id:id||'acct_synthetic_platform',object:'account',charges_enabled:true,payouts_enabled:true,details_submitted:true}),create:async(p,o)=>{writes++;return {id:'acct_created',object:'account',type:'express',metadata:p.metadata};}},balance:{retrieve:async()=>({livemode:false})},accountLinks:{create:async()=>{writes++;return {url:'https://connect.example.test/synthetic'};}},...overrides};stripe.__setStripeClientForTest(client,definitions);const context=await stripe.verifyStripeTransferContext({platform:'legacy'});return {context,client,writes:()=>writes};}
test('M10 lookup timeout/auth/not-found/wrong identity never creates accounts or links',async()=>{for(const kind of ['timeout','auth','not-found','wrong']){const f=await fakeProvider();f.client.accounts.retrieve=async()=>{if(kind==='wrong')return {id:'acct_wrong',object:'account'};throw Error(kind);};await assert.rejects(stripe.getConnectAccountStatus('acct_connected',f.context));await assert.rejects(stripe.createConnectOnboardingLink('acct_connected','https://example.test/return','https://example.test/refresh',f.context));assert.equal(f.writes(),0);}});
test('M10 new account sends fixed key once and validates owner/intent evidence',async()=>{const f=await fakeProvider();let options;f.client.accounts.create=async(p,o)=>{options=o;return {id:'acct_created',object:'account',type:'express',metadata:p.metadata};};assert.deepEqual(await stripe.createConnectAccount('owner',{context:f.context,idempotencyKey:'fixed-key',intentId:'intent'}),{account_id:'acct_created'});assert.deepEqual(options,{idempotencyKey:'fixed-key',maxNetworkRetries:0});f.client.accounts.create=async()=>({id:'acct_created',object:'account',type:'express',metadata:{}});await assert.rejects(stripe.createConnectAccount('owner',{context:f.context,idempotencyKey:'fixed-key',intentId:'intent'}),/evidence/);});
test('M10 onboarding existing mapping uses verified same account without create',async()=>{const f=await fakeProvider();f.client.accounts.create=async()=>{throw Error('Unexpected account creation');};assert.equal((await stripe.createConnectOnboardingLink('acct_connected','https://example.test/return','https://example.test/refresh',f.context)).account_id,'acct_connected');assert.equal(f.writes(),1);});
test('M10 corrupted or changed Connect intent store fails closed after restart',()=>{const file=path.join(dir,'corrupt.json');intents.initializeConnectIntents(file,{checkpoint_id:'synthetic',manifest_sha256:'a'.repeat(64),inventory_complete:true,approval_ref:'approval'});const s=intents.createConnectIntentStore({file});const a=s.prepare({account_id:'owner-corrupt',context,idempotency_key:'fixed',approval_ref:'approval',evidence_ref:'proof'});const data=JSON.parse(fs.readFileSync(file));data.intents[a.intent_id].account_id='changed';fs.writeFileSync(file,JSON.stringify(data));assert.throws(()=>s.all(),/Invalid/);});
test('M10 mapping publication refuses a copied capability even with approved evidence',async()=>{const f=await fakeProvider();assert.throws(()=>accounts.setStripeConnectMapping('owner',{...f.context},'acct_connected',evidence),/context/);});
test('M08 Checkout uses fixed key/correlation once and validates full safe response',async()=>{const f=await fakeProvider();let captured;f.client.checkout={sessions:{create:async(p,o)=>{captured={p,o};return {id:'cs_synthetic',object:'checkout.session',mode:'payment',livemode:false,amount_total:1000,currency:'usd',metadata:p.metadata,expires_at:Math.floor(Date.now()/1000)+2100,url:'https://checkout.example.test/synthetic'};}}};const result=await stripe.createCheckoutSession('owner','starter','https://example.test',{context:f.context,idempotencyKey:'fixed',intentId:'intent'});assert.equal(result.session_id,'cs_synthetic');assert.deepEqual(captured.o,{idempotencyKey:'fixed',maxNetworkRetries:0});assert.equal(captured.p.metadata.auxilo_checkout_intent_id,'intent');f.client.checkout.sessions.create=async()=>({id:'cs_synthetic'});await assert.rejects(stripe.createCheckoutSession('owner','starter','https://example.test',{context:f.context,idempotencyKey:'fixed',intentId:'intent'}),/evidence/);});
// Execute the actual production Hono route with real durable stores and fake providers.
const vm=require('node:vm');const {Hono}=require('hono');const crypto=require('node:crypto');
const source=fs.readFileSync(path.join(__dirname,'..','server.js'),'utf8');const routeSource=source.slice(source.indexOf("app.post('/account/connect-stripe'"),source.indexOf('// POST /withdraw/stripe',source.indexOf("app.post('/account/connect-stripe'")));
async function connectFixture(options={}) {
 const f=await fakeProvider();const file=path.join(dir,crypto.randomUUID()+'.json');const ref={checkpoint_id:'synthetic',manifest_sha256:'a'.repeat(64),inventory_complete:true,approval_ref:'approval'};if(!options.missing)intents.initializeConnectIntents(file,ref);const store=intents.createConnectIntentStore({file});
 const account={id:'owner',stripe_connect_dispositions:{legacy:{...evidence,stripe_platform_account_id:'acct_synthetic_platform'}}};if(options.legacy)account.stripe_connect_id='acct_historical';if(options.unapproved)delete account.stripe_connect_dispositions;
 fs.writeFileSync(process.env.AUXILO_ACCOUNTS_FILE,JSON.stringify({owner:account}));if(options.mapping)accounts.setStripeConnectMapping('owner',f.context,'acct_connected',evidence);
 let createCalls=0,linkCalls=0,locked=false,tail=Promise.resolve();f.client.accounts.create=async(p)=>{assert.equal(locked,true);createCalls++;if(options.timeout)throw Error('provider timeout');return {id:'acct_created',object:'account',type:'express',metadata:p.metadata};};f.client.accountLinks.create=async()=>{linkCalls++;if(options.linkFailure&&linkCalls===1)throw Error('link unavailable');return {url:'https://connect.example.test/link'};};if(options.lookupFailure)f.client.accounts.retrieve=async()=>{throw Error('lookup failed');};
 const control={ready:true,armed:false,generation:0,intake_platform:'legacy',allow_connect_creation:!options.paused};const controls={getMigrationControl:()=>control,assertActionAllowed:()=>{if(options.paused)throw Error('paused');return control;}};
 const ctx={app:new Hono(),process:{env:{CUSTODIAL_WITHDRAW_ENABLED:'true',BASE_URL:'https://example.test'}},fs,crypto,ACCOUNTS_FILE:process.env.AUXILO_ACCOUNTS_FILE,accounts:{owner:account},paymentsEnabled:()=>true,paymentsDisabledBody:()=>({}),hasAcceptedCurrentTos:()=>true,termsNotAcceptedResponse:c=>c.json({},403),requireAuth:async(c,next)=>{c.set('accountId','owner');await next();},getConnectAccountStatus:stripe.getConnectAccountStatus,fatalFinancialStorage:e=>{throw e;},acquireAccountLock:async()=>{const previous=tail;let release;tail=new Promise(r=>release=r);await previous;locked=true;return()=>{locked=false;release();};},require:name=>name==='./lib/stripe.js'?{...stripe,getStripeStatus:()=>({configured:true})}:name==='./lib/accounts'?accounts:name==='./lib/stripe-platforms'?{...registry,getVerifiedClient:async()=>({context:f.context,client:f.client})}:name==='./lib/stripe-connect-intents'?{createConnectIntentStore:()=>store}:name==='./lib/stripe-migration-controls'?controls:require(name)};
 vm.createContext(ctx);vm.runInContext(routeSource,ctx);return {store,ctx,counts:()=>({createCalls,linkCalls}),post:()=>ctx.app.request('/account/connect-stripe',{method:'POST'})};
}
test('M10 route existing mapped lookup failure never creates replacement',async()=>{const f=await connectFixture({mapping:true,lookupFailure:true});assert.equal((await f.post()).status,503);assert.deepEqual(f.counts(),{createCalls:0,linkCalls:0});});
test('M10 route legacy single ID without proven mapping is retained unresolved',async()=>{const f=await connectFixture({legacy:true});assert.equal((await f.post()).status,409);assert.deepEqual(f.counts(),{createCalls:0,linkCalls:0});assert.equal(accounts.loadAccounts().owner.stripe_connect_id,'acct_historical');});
test('M10 route unknown account creation never resends across retries',async()=>{const f=await connectFixture({timeout:true});assert.equal((await f.post()).status,409);assert.equal(f.store.all()[0].state,'unknown');assert.equal((await f.post()).status,409);assert.deepEqual(f.counts(),{createCalls:1,linkCalls:0});});
test('M10 route account_created survives link failure and reuses same account',async()=>{const f=await connectFixture({linkFailure:true});assert.equal((await f.post()).status,503);assert.equal(f.store.all()[0].state,'account_created');assert.equal((await f.post()).status,200);assert.deepEqual(f.counts(),{createCalls:1,linkCalls:2});assert.equal(f.store.all()[0].state,'completed');});
test('M10 concurrent route requests create exactly one mapped account',async()=>{const f=await connectFixture();const rs=await Promise.all([f.post(),f.post()]);assert.deepEqual(rs.map(r=>r.status),[200,200]);assert.deepEqual(f.counts(),{createCalls:1,linkCalls:1});});
for(const options of [{missing:true},{unapproved:true},{paused:true}])test('M10 missing evidence/store or action pause makes zero provider writes '+JSON.stringify(options),async()=>{const f=await connectFixture(options);assert.ok((await f.post()).status>=400);assert.deepEqual(f.counts(),{createCalls:0,linkCalls:0});});
