'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const op=require('../lib/stripe-production-operator');const {digestJSON}=require('../lib/stripe-transfer-persistence');const {PLATFORMS}=require('../lib/stripe-object-origins');
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
function fixture(t){const base=fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()),'operator-test-'));t.after(()=>fs.rmSync(base,{recursive:true,force:true}));const inputDir=path.join(base,'checkpoint'),outputDir=path.join(base,'rehearsal');fs.mkdirSync(inputDir,{mode:0o700});fs.mkdirSync(path.join(inputDir,'wal'),{mode:0o700});const records={'earnings.json':{synthetic:{pending_balance:2}},'accounts.json':{synthetic:{id:'synthetic'}},'credits.json':{},'purchases.jsonl':'','withdrawals.jsonl':'','account-holds.json':{},'checkout-sessions.json':{}};for(const[name,value]of Object.entries(records))fs.writeFileSync(path.join(inputDir,name),typeof value==='string'?value:JSON.stringify(value),{mode:0o600});require('../lib/stripe-transfer-attempts').initializeAttemptStore(path.join(inputDir,'stripe-transfer-attempts.json'),{sha256:'a'.repeat(64),inventory_complete:true,positive_history_attestation:true,history_interval:{start:'2026-01-01',end:'2026-10-05'},platforms:Object.entries(PLATFORMS).map(([stripe_platform,stripe_platform_account_id])=>({stripe_platform,stripe_platform_account_id,livemode:false}))});const files={};for(const name of fs.readdirSync(inputDir).filter(n=>n!=='wal'))files[name]={sha256:sha(fs.readFileSync(path.join(inputDir,name))),kind:name.endsWith('.jsonl')?'jsonl':'json'};const manifest={schema_version:1,checkpoint_id:'synthetic-checkpoint',created_at:'2026-10-05T00:00:00Z',platforms:Object.entries(PLATFORMS).map(([alias,account_id])=>({alias,account_id,mode:'test',history:{from:'2026-01-01',to:'2026-10-05',evidence_ref:'synthetic-positive-history'}})),files,wal:{entries:[],listing_sha256:sha('[]')},objects:[],hold_origins:[],initialization:Object.fromEntries(['stripe-object-origins.json','stripe-checkout-intents.json','stripe-event-receipts.json','stripe-connect-intents.json'].map(n=>[n,'absent'])),approval_ref:'synthetic-planning'};return{inputDir,outputDir,manifest,candidateSha:'a'.repeat(40)};}
function planned(t){const f=fixture(t);return{...f,plan:op.createOperatorPlan(f)};}
function approval(plan){return{schema_version:1,execution_approval_ref:'synthetic-execution',plan_checksum:plan.checksum,app_name:'synthetic-app',machine_id:'synthetic-machine',candidate_sha:plan.candidate_sha,target_dir:'/app/data',window_start:'2026-10-06T00:00:00Z',window_end:'2026-10-06T00:30:00Z',installed_hashes:plan.installed_hashes,writer_stopped:true};}
function observation(plan){return{operator_entrypoint:true,platform:'linux',uid:0,target_uid:1000,target_gid:1000,target_dir:'/app/data',app_name:'synthetic-app',machine_id:'synthetic-machine',candidate_sha:plan.candidate_sha,installed_hashes:plan.installed_hashes,observed_at:'2026-10-06T00:10:00Z',other_node_processes:[],listening_sockets:[],process_scan_complete:true,socket_scan_complete:true};}
test('inspector reports each missing historical source without invented totals',t=>{const f=fixture(t);for(const n of ['withdrawals.jsonl','account-holds.json','checkout-sessions.json','stripe-transfer-attempts.json'])fs.unlinkSync(path.join(f.inputDir,n));const r=op.inspectCheckpoint(f.inputDir);assert.deepEqual(r.missing.sort(),['account-holds.json','checkout-sessions.json','stripe-transfer-attempts.json','withdrawals.jsonl']);assert.equal(r.inventory_complete,false);assert.equal(r.totals,null);assert.throws(()=>op.createOperatorPlan(f));});
test('inspector refuses symlinked file and malformed JSON',t=>{const f=fixture(t);fs.writeFileSync(path.join(f.inputDir,'earnings.json'),'{');assert.ok(op.inspectCheckpoint(f.inputDir).malformed.includes('earnings.json'));fs.unlinkSync(path.join(f.inputDir,'earnings.json'));fs.symlinkSync(path.join(f.inputDir,'accounts.json'),path.join(f.inputDir,'earnings.json'));assert.throws(()=>op.inspectCheckpoint(f.inputDir));});
test('planning is sealed, source-bound and read only',t=>{const f=fixture(t),before=fs.readdirSync(f.inputDir);const p=op.createOperatorPlan(f);assert.equal(p.migration.economic_before,p.migration.economic_after);assert.equal(p.source.absent_names.length,4);assert.deepEqual(fs.readdirSync(f.inputDir),before);assert.equal(fs.existsSync(f.outputDir),false);assert.equal(p.checksum,op.validateOperatorPlan(p).checksum);});
test('rehearsal preserves logs/economics and creates conservative bound artifacts privately',t=>{const f=planned(t);const result=op.rehearse(f);assert.equal(result.state,'completed');for(const name of ['purchases.jsonl','withdrawals.jsonl'])assert.deepEqual(fs.readFileSync(path.join(f.inputDir,name)),fs.readFileSync(path.join(f.outputDir,name)));const c=JSON.parse(fs.readFileSync(path.join(f.outputDir,'stripe-migration-control.json')));assert.equal(c.phase,'paused');assert.equal(c.intake_platform,null);assert.equal(c.allow_checkout,false);assert.equal(c.allow_connect_creation,false);assert.equal(c.allow_builder_transfer,false);assert.equal(fs.statSync(f.outputDir).mode&0o777,0o700);for(const name of fs.readdirSync(f.outputDir).filter(n=>fs.statSync(path.join(f.outputDir,n)).isFile()))assert.equal(fs.statSync(path.join(f.outputDir,name)).mode&0o777,0o600);assert.throws(()=>op.rehearse(f));});
test('stale source, added WAL and changed plan each refuse rehearsal before output creation',t=>{for(const change of ['source','wal','plan']){const f=planned(t);if(change==='source')fs.writeFileSync(path.join(f.inputDir,'earnings.json'),'{}');if(change==='wal')fs.writeFileSync(path.join(f.inputDir,'wal','extra'),'{}');if(change==='plan')f.plan.migration.entries[0].bytes_base64='e30=';assert.throws(()=>op.rehearse(f));assert.equal(fs.existsSync(f.outputDir),false);}});
test('runtime pure validator requires exact approval and complete stopped-writer evidence',t=>{const f=planned(t),a=approval(f.plan),o=observation(f.plan);assert.equal(op.validateRuntimeAttestation(o,a,f.plan),true);for(const patch of [{operator_entrypoint:false},{platform:'darwin'},{uid:1000},{target_uid:0},{app_name:'wrong'},{machine_id:'wrong'},{candidate_sha:'b'.repeat(40)},{target_dir:'/tmp'},{observed_at:'2026-10-06T01:00:00Z'},{other_node_processes:[12]},{listening_sockets:['tcp:8080']},{process_scan_complete:false},{socket_scan_complete:false},{installed_hashes:{}}])assert.throws(()=>op.validateRuntimeAttestation({...o,...patch},a,f.plan));assert.throws(()=>op.validateRuntimeAttestation(o,{...a,plan_checksum:'0'.repeat(64)},f.plan));});
test('production entry never accepts injected fake runtime observation',t=>{const f=planned(t);assert.throws(()=>op.maintain({targetDir:f.inputDir,plan:f.plan,approval:approval(f.plan),observation:observation(f.plan)}));assert.equal(fs.existsSync(path.join(f.inputDir,'stripe-migration-journal.json')),false);});
test('every rehearsal crash boundary recovers forward including control and marker',t=>{for(let crash=1;crash<=16;crash++){const f=planned(t);assert.throws(()=>op.rehearse({...f,afterWrite:(_name,index)=>{if(index===crash)throw Error('synthetic-crash');}}),/synthetic-crash/);const j=JSON.parse(fs.readFileSync(path.join(f.outputDir,'stripe-migration-journal.json')));assert.ok(['applying','completed'].includes(j.state));const result=op.recoverRehearsal(f);assert.equal(result.state,'completed');}});
test('recovery refuses disappearance of historical file and unrelated output change',t=>{for(const mode of ['missing','changed']){const f=planned(t);assert.throws(()=>op.rehearse({...f,afterWrite:()=>{throw Error('crash');}}));const file=path.join(f.outputDir,'earnings.json');if(mode==='missing')fs.unlinkSync(file);else fs.writeFileSync(file,'{}');assert.throws(()=>op.recoverRehearsal(f));}});
test('self-consistent forged journal entry and mismatched conservative control refuse recovery',t=>{for(const kind of ['journal','control']){const f=planned(t);assert.throws(()=>op.rehearse({...f,afterWrite:()=>{throw Error('crash');}}));if(kind==='journal'){const file=path.join(f.outputDir,'stripe-migration-journal.json'),j=JSON.parse(fs.readFileSync(file));j.entries[0].bytes_base64=Buffer.from('{"tampered":true}\n').toString('base64');j.entries[0].after_sha256=sha('{"tampered":true}\n');delete j.checksum;j.checksum=digestJSON(j);fs.writeFileSync(file,JSON.stringify(j));}else fs.writeFileSync(path.join(f.outputDir,'stripe-migration-control.json'),'{}');assert.throws(()=>op.recoverRehearsal(f));}});

test('ownership policy preserves existing owners and assigns new files to verified node directory',()=>{assert.deepEqual(op.selectOutputOwner({uid:1000,gid:1000},null),{uid:1000,gid:1000});assert.deepEqual(op.selectOutputOwner({uid:1000,gid:1000},{uid:1200,gid:1300}),{uid:1200,gid:1300});assert.throws(()=>op.selectOutputOwner({uid:0,gid:0},null));});
test('private artifact failure before rename leaves destination absent and cleans temporary file',t=>{const f=fixture(t),target=path.join(path.dirname(f.inputDir),'private-plan.json'),original=fs.fsyncSync;fs.fsyncSync=()=>{throw Error('synthetic-fsync-failure');};try{assert.throws(()=>op.writePrivateArtifact(target,{private:'synthetic'}),/synthetic-fsync/);}finally{fs.fsyncSync=original;}assert.equal(fs.existsSync(target),false);assert.equal(fs.readdirSync(path.dirname(target)).some(name=>name.endsWith('.tmp')),false);});
test('CLI defaults to masked inspection and refuses mutations without named approval',t=>{const f=fixture(t),{main}=require('../scripts/stripe-production-operator');const r=main(['--input',f.inputDir]);assert.equal(r.state,'inspected');assert.equal(JSON.stringify(r).includes('synthetic-checkpoint'),false);assert.throws(()=>main(['--mode','maintain','--target',f.inputDir]));assert.throws(()=>main(['--mode','rehearse','--input',f.inputDir]));});
test('recovery rejects unexpected created store and symlink without mutation',t=>{const f=planned(t);assert.throws(()=>op.rehearse({...f,afterWrite:()=>{throw Error('crash');}}));const name='stripe-checkout-intents.json',file=path.join(f.outputDir,name);fs.writeFileSync(file,'{}');assert.throws(()=>op.recoverRehearsal(f));fs.unlinkSync(file);fs.symlinkSync(path.join(f.inputDir,'earnings.json'),file);assert.throws(()=>op.recoverRehearsal(f));});

test('source comparison ignores only a verified current-process maintenance lock',t=>{const f=planned(t),snapshot=require('../lib/stripe-migration-journal').readMigrationCheckpoint(f.inputDir,f.manifest);snapshot.presentNames.push('.stripe-production-maintenance.lock');assert.equal(op.validateSourceSnapshot(snapshot,f.plan,{pid:process.pid}),true);assert.throws(()=>op.validateSourceSnapshot(snapshot,f.plan,{pid:process.pid+1}));assert.throws(()=>op.validateSourceSnapshot(snapshot,f.plan));snapshot.presentNames.push('foreign-artifact');assert.throws(()=>op.validateSourceSnapshot(snapshot,f.plan,{pid:process.pid}));});
test('recovery refuses an unexpected root artifact',t=>{const f=planned(t);assert.throws(()=>op.rehearse({...f,afterWrite:()=>{throw Error('crash');}}));fs.writeFileSync(path.join(f.outputDir,'unexpected.json'),'{}');assert.throws(()=>op.recoverRehearsal(f),/ROOT_DRIFT/);});

test('socket evidence permits only observed hallpass22 and init UNIX infrastructure',()=>{const sockets=[{kind:'tcp',port:22,inode:'1'},{kind:'unix',inode:'2'}],owners={'1':[{pid:2,executable:'/synthetic/hallpass'}],'2':[{pid:1,executable:'/synthetic/init'}]};assert.deepEqual(op.classifyListeningSockets(sockets,owners,true),[]);});
test('unknown owner on22 and application listener3000 remain forbidden',()=>{for(const[port,executable]of [[22,'unknown'],[3000,'node'],[3000,'hallpass']])assert.equal(op.classifyListeningSockets([{kind:'tcp',port,inode:'1'}],{'1':[{pid:2,executable:'/synthetic/'+executable}]},true).length,1);});
test('unknown UNIX owner and mixed ownership remain forbidden',()=>{assert.equal(op.classifyListeningSockets([{kind:'unix',inode:'1'}],{'1':[{pid:2,executable:'/synthetic/other'}]},true).length,1);assert.equal(op.classifyListeningSockets([{kind:'tcp',port:22,inode:'1'}],{'1':[{pid:1,executable:'/synthetic/hallpass'},{pid:2,executable:'/synthetic/other'}]},true).length,1);});
test('unreadable or unowned socket evidence fails closed',()=>{assert.throws(()=>op.classifyListeningSockets([],{},false));assert.throws(()=>op.classifyListeningSockets([{kind:'tcp',port:22,inode:'missing'}],{},true));});
function killBeforeRename(f,target){const cp=require('node:child_process'),modulePath=require.resolve('../lib/stripe-production-operator');const script=`const fs=require('fs'),path=require('path'),op=require(${JSON.stringify(modulePath)}),f=JSON.parse(process.argv[1]);const rename=fs.renameSync;fs.renameSync=(from,to)=>{if(path.basename(to)===${JSON.stringify(target)}&&(${JSON.stringify(target)}==='stripe-migration-journal.json'||fs.existsSync(path.join(f.outputDir,'stripe-migration-journal.json'))))process.kill(process.pid,'SIGKILL');return rename(from,to);};op.rehearse(f);`;const result=cp.spawnSync(process.execPath,['-e',script,JSON.stringify(f)],{encoding:'utf8'});assert.equal(result.signal,'SIGKILL',result.stderr);}
for(const target of ['stripe-migration-journal.json','accounts.json','stripe-migration-control.json','stripe-migration-armed.json'])test('actual SIGKILL before '+target+' rename recovers only authoritative state',t=>{const f=planned(t);killBeforeRename(f,target);assert.ok(fs.readdirSync(f.outputDir).some(name=>name.endsWith('.tmp')));assert.equal(op.recoverRehearsal(f).state,'completed');assert.equal(fs.readdirSync(f.outputDir).some(name=>name.endsWith('.tmp')),false);assert.equal(JSON.parse(fs.readFileSync(path.join(f.outputDir,'earnings.json'))).synthetic.pending_balance,2);});
for(const invalid of ['wrong-plan','random','wrong-mode'])test('recovery refuses '+invalid+' staging artifact',t=>{const f=planned(t);killBeforeRename(f,'accounts.json');const stages=fs.readdirSync(f.outputDir).filter(n=>n.endsWith('.tmp'));const file=path.join(f.outputDir,stages[0]);if(invalid==='wrong-mode')fs.chmodSync(file,0o644);else fs.renameSync(file,path.join(f.outputDir,invalid==='random'?'accounts.json.random.tmp':'accounts.json.operator-'+('0'.repeat(64))+'.tmp'));assert.throws(()=>op.recoverRehearsal(f));});

test('plan-bound stage ownership allows only final owner or transient effective-root owner',()=>{const expected={uid:1000,gid:1000},operator={uid:0,gid:0};assert.equal(op.validateStagingOwnership({mode:0o600,uid:1000,gid:1000},expected,operator),true);assert.equal(op.validateStagingOwnership({mode:0o600,uid:0,gid:0},expected,operator),true);assert.throws(()=>op.validateStagingOwnership({mode:0o600,uid:0,gid:99},expected,operator));assert.throws(()=>op.validateStagingOwnership({mode:0o600,uid:123,gid:123},expected,operator));assert.throws(()=>op.validateStagingOwnership({mode:0o4600,uid:0,gid:0},expected,operator));});
test('initial journal stage cannot restart after source drift or without exact stage',t=>{for(const change of ['drift','absent']){const f=planned(t);killBeforeRename(f,'stripe-migration-journal.json');if(change==='drift')fs.writeFileSync(path.join(f.outputDir,'earnings.json'),'{}');else for(const n of fs.readdirSync(f.outputDir).filter(n=>n.endsWith('.tmp')))fs.unlinkSync(path.join(f.outputDir,n));assert.throws(()=>op.recoverRehearsal(f));assert.equal(fs.existsSync(path.join(f.outputDir,'stripe-migration-journal.json')),false);}});
